### ISSUE TITLE
Several TT changes

### ISSUE THREAD

**Issue by GrooveOG** [saesrpg/saesrpg-gang#102]
Hello!

- We would like to change our spawn coordinates to these: https://pastebin.com/gxSf3vBe
- "Tuga Thugs Novato" has to be added to the skill running script pls & should be allowed to sell fighting skill & drug (note tuga thugs spawn is fine on both of these).

- "Tuga Thugs Novato" & "Tuga Thugs" will be spawning with colts and dus pls give it duals colts ability. 

- All our base gates have to be adapted to the new spawn (replace Tuga Thugs Respected with Tuga Thugs Novato / any eventual locked markers though I doubt there is any).

- Regarding the shaders, we currently have 3 shaders (one on all our 3 vagos skins); pls make it so they are enabled both on "Tuga Thugs" & "Tuga Thugs Novato". 
--- We also would like to request a fourth shader on the skin gangrl3 [ID:195] (enable it on both spawns pls, link here: to be given in pvt)

- We would like to request a gate that mysteriously dissapeared in our current interior: https://pastebin.com/0ZbQDUHt

- We would like to re-request an old interior we used to have which mysteriously dissapeared aswell a few years ago: mapping will be given in pvt
-- with these as gates:  https://pastebin.com/hy7jchvA

-- with this as marker to warp to it: 
https://pastebin.com/w6VNsD7h

**Comment by SAESKain** [comment]
Private stuff is issue #1 on private git for whoever sorts this

**Comment by ghost** [comment]
@SAESKain can you update sell scripts with new class

**Comment by GrooveOG** [comment]
Hej

Would like to request a little fix, mapped it but I'm unable to update the vehicle warp myself

The marker named "TTsecondarygarage" will have to be adapted for its exit coords, shoud look like that now: https://pastebin.com/Ufjj7sza.

Could the classes "Arms Assassins", "Arms Assassins Novice", "Black~Bullets", "Black~Bullets HQ" be added to "TTshore" marker restriction (in addition to the 2 TT spawns which are already there and finely working)

PMed the base mapping file to ikzelf & kain

Thanks mens!!
