### ISSUE TITLE
The Outfit spawn update

### ISSUE THREAD

**Issue by SAES-Jay** [saesrpg/saesrpg-gang#106]
Requesting Dual Colt for 'The Outfit' spawn.

Spawn codes as follows;

			<spawn id="The Outfit" skin="98,120,233" x="-685" y="969.5" z="12.48" rot="180" weapons="2,1;41,5000;22,250;27,250;32,350;31,450;34,150;16,10;46,1" 
			description="An organised English crime family who specialise in import and export." r="105" g="105" b="105" restricted="gang,The_Outfit" ganglevelrestriction="0" />

			<spawn id="The Outfit Lynchpin" skin="186" x="-685" y="969.5" z="12.48" rot="180" weapons="2,1;41,5000;24,250;27,250;32,350;31,450;34,150;16,10;46,1" 
			description="The Lynchpin of an organised English crime family who specialise in import and export." r="105" g="105" b="105" restricted="gang,The_Outfit" ganglevelrestriction="4" />

**Comment by ghost** [comment]
Dual colts :ok:
