### ISSUE TITLE
SAI - Changes

### ISSUE THREAD

**Issue by bas260** [saesrpg/saesrpg-gang#11]
Hello,

**Construction Panel**
I'd like to have the construction panel re-added to the trooper (sai-d) spawn. 

**Gates**
And could the sapa group be (added) allowed to the gates? So they can open and use the base for roleplay purposes. To clarify I am referring to both the interior and exterior gates. 

**Vehicles**
*To be removed*; bullet, admiral, FBI truck (2x) and all the police SF in the north centre garage, police SF.

*To be moved* The crown victorias stuffed in the corner. I want them to be moved to the centre garage. And another 3 to be added. So you'd have 6 Crown Vics in the the the centre garage. If you require screenshots for clarification then please message me on discord. 
And could all the police LV also be moved into the top left garage (when facing the north).
These vehicles also have to be painted #434994 & #ffffff. In blue / white / blue. And I don't know if we're allowed but could nitro be added on the vehicles which don't have it.

**Comment by nicusi** [comment]
Vehicles sorted, inform me on discord if anything needs to be changed.
