### ISSUE TITLE
ICE Reward Changes

### ISSUE THREAD

**Issue by 00Sam00** [saesrpg/saesrpg-gang#110]
Hello,
We would like to Change the Spawn Code: 

`<spawn id="ICE Special Unit" skin="228" x="2509.43384" y="2521.57690" z="10.82031" rot="270" weapons="3,1;23,200;27,150;29,450;31,450;34,150;46,1;17,10" description="ICE – Immigration enforcement is the largest single area of responsibility for ICE. While certain responsibilities and close cooperation with S.A. Customs and Border Protection." r="000" g="101" b="255" restricted="squad,ICE-POLICE" ganglevelrestriction="3" />
`
----------------------------------------------------

Also we did not got our Billboard from the level 5 Rewards, so i will request it again.
Here is the PNG file
![ICE Billboard](https://user-images.githubusercontent.com/46724105/63305740-be2bec80-c2f0-11e9-9b66-b0fe3338837b.png)

**Comment by ghost** [comment]
What do you want to change of your spawn because its the exact same as the current one

**Comment by 00Sam00** [comment]
There should be added combat shotgun instead of shotgun only for the special unit spawn.

**Comment by 00Sam00** [comment]
Could someone please add the combat shotgun to the special unit spawn? Waiting now longer time for it. Thanks

**Comment by SAESKain** [comment]
weps live next push, billboard not as ur not level 5 anymore
