### ISSUE TITLE
CripZ change and request

### ISSUE THREAD

**Issue by adriano3756** [saesrpg/saesrpg-gang#111]
Greetings,
We would like to request on replacing our lovely deagle with dual colts for only `CripZ OG` spawn

And also some reward change regarding with our vehicles:
1. remove buffalo infront of gang interior
2. remove nrg, turismo and hotring racer located under the bridge
3. add maverick, picador, broken glendale
4. add sandking at the NRG's exact location

Locations will be settled ingame with me
Thanks.

**Comment by ghost** [comment]
Duals added, vehicles contact me or nicusi ingame
