### ISSUE TITLE
OverdoseCrime Level 5 Rewards

### ISSUE THREAD

**Issue by Mrwann** [saesrpg/saesrpg-gang#116]
Hello there.

Walking Style: 
-------------
MOVE_GANG1

Selling abilities:
----------------
Drugs / Weapons

Additions:
----------
We have an ATM mapped In the base, we'd like It to work, and we also would love to have dual colts.

Exterior files:
--------------
https://www.mediafire.com/file/vph1rr4bnh2bsbd/Exterior.rar/file

Interior files:
------------
https://www.mediafire.com/file/b6eu24ae584lbwb/Interior_files.rar/file

Interior Shaders:
------------------
https://www.mediafire.com/file/ojv4zzp3c46plo2/Interior.rar/file

All the markers file:
----------------------
https://www.mediafire.com/file/lhzmpecsnp1bk94/OCMARKERS.txt/file

Spawn:
---------
https://www.mediafire.com/file/p1wte2jbdhr61yl/OCSPAWN.txt/file

The GR Safe code:
--------------------
< safe id="OverdoseCrime" x="-1288.099609375" y="2619.900390625" z="115.69999694824" rot="0" restricted="gang,OverdoseCrime." />

Skin shaders:
----------------
Skin name: Torino
Skin ID: 295
File: https://www.mediafire.com/view/lp75tb6txyv7rel/The_one_we%27ll_use.png/file

Skin name: somyri
Skin ID: 186
File: https://www.mediafire.com/view/8tssiqh9a9208ec/oc100done.png/file

We'd like to add that we hope If you can fix the 2nd skin (girl skin) of us, Some people see It all black or all white and that's a bug I believe, Hope you can fix It too please.

I guess that's all, Thank you!

**Comment by SAESKain** [comment]
Please convert your base to .lua format.

Re-request properly. Back of the line.
