### ISSUE TITLE
Comando da Capital Rewards Request

### ISSUE THREAD

**Issue by cdcJulius** [saesrpg/saesrpg-gang#12]
Base Mapping: http://y0b.net/cdc-lvl5-base.zip
Gates Code: https://pastebin.com/VRVjDRdU
Warp codes: https://pastebin.com/jxbMvHa3
CDC Spawn code:  https://pastebin.com/tE0wbWth
Base Shaders: http://www.mediafire.com/file/52zf4p7xpn0o3f2/cdc_base_shader.zip/file
Base Shaders Code: https://pastebin.com/HCHmfHM1
Skin Shaders: https://www.mediafire.com/file/kbez1jzzmqmh0qb/skin_shaders.zip/file

Secondary Job: 
/sellarms

Vehicles:
3x nrg-500
2x Maverick
2x savana
1x dodo
1x huntley
1x sultan
1x infernus
1x Burrito
1x Bus

atm,npc's etc.

**Comment by SAESKain** [comment]
"atm,npc's etc." If you want those you gotta give the coords/correct format cus as I keep saying to everyone lately I'm not a mind reader :shrug:

**Comment by SAESKain** [comment]
markers={
{2529.7002,-956.90039,106.8,'arrow',1},
}


for id,d in ipairs(markers) do
    local marker=createMarker(d[1],d[2],d[3],d[4],d[5])
end

and what's this for in your base files?

**Comment by cdcJulius** [comment]
ATM: 2530,-953,106
npc1 Skin ID 123 : 2492,-968,83 - Anim /tme
npc2 Skin ID 123:2459.-968,80 -   Anim /gtalk 4
npc3 Skin ID 293:2455,-968,80 - Anim /gtalk 2

this is probably a warp marker that I forgot to remove from the mapping
