### ISSUE TITLE
VeC level 2 rewards

### ISSUE THREAD

**Issue by SAESHenry** [saesrpg/saesrpg-gang#120]
**Gang spawn:** 
`<spawn id="Vandalos de El Corona" skin="109,298" x="1665.6999511719" y="-2133.3000488281" z="13.60" rot="287" weapons="1,1;22,75;25,50;28,150;46,1;41,4000" 
description="Violent latin street gang from the neighborhood of El Corona." r="179" g="159" b="51" restricted="gang,Vandalos_de_El_Corona" ganglevelrestriction="0" />`
________
**Gang spawn shader (lsv2 - 109)**
(Attached file)
![vecshader](https://user-images.githubusercontent.com/53539807/66003784-55b35c00-e4a7-11e9-843d-78e70a68d284.png) 
_________
**Walking style**
MOVE_GANG2
_____
**Primary job:** /sell drugs
_______
**Exterior map in .lua** 
[vec-exterior.txt](https://github.com/saesrpg/saesrpg-gang/files/3678648/vec-exterior.txt)
_______
**Exterior map shaders**
[vecexteriorshaders.txt](https://github.com/saesrpg/saesrpg-gang/files/3681381/vecexteriorshaders.txt)

**Shaders images**
http://www.mediafire.com/file/88cd7unr35a7970/vecshaders.rar/file
______
**Safe in position:** x= 1645.5    y= -2137.8994140625   z= 14.60000038147 Rotation Z = 59.990844726563
________
**Vehicles**
1) Sabre primary color: #B39F33 Second: Black color with nitro10x
2) Bucanner primary color #B39F33 With nitro10x
3) Savanna primary color #B39F33 with nitro 10x
_____
Safedisk location will be told ingame
_______
**Graffiti**
http://www.mediafire.com/file/bb1n9456pju36oo/graffiti.dds/file

**Comment by SAESKain** [comment]
https://saesrpg.uk/topic/5633/shader-size-limits

Make sure all shaders comply to the above rules

**Comment by Shekelbergx** [comment]
http://www.mediafire.com/file/88cd7unr35a7970/vecshaders.rar/file

**Comment by SAESKain** [comment]
Same as OC....

The base hasn't been converted to .lua.

Re-request it properly, back of the line.
