### ISSUE TITLE
MMC's Level 2 rewards

### ISSUE THREAD

**Issue by Sira188** [saesrpg/saesrpg-gang#121]
**Spawn Point :** 

<spawn id="Mongols MC" skin="100,248" x="346.5" y="-102.30000305176" z=" 1.4800000190735" rot="180" weapons="5,1;22,75;25,50;32,150;41,5000;46,1" description="For the law we are just a normal mechanics, but we are way more than that. We are doing everything we could do profit from. We are the Mongols Motorcycle. Mongols forever, forever Mongols" r="249" g="233" b="172" restricted="gang,Mongols_MC"/>

----------------------------------------------------------------------------------------------------------

**Base mapping :** 

http://www.mediafire.com/file/oxbk437znbeerg3/MMC-base.lua.lua/file

**Base's shaders : **

http://www.mediafire.com/file/vsyoh51ci5uxlge/base_shaders.rar/file

**Base's location :** 

https://imgur.com/a/zXvmRjr
----------------------------------------------------------------------------------------------------------

**Skin shader : 

( skin id:100)**
http://www.mediafire.com/file/20lkryzgt79n7q8/skin_shader.dds.dds/file

----------------------------------------------------------------------------------------------------------

**Walking style**
MOVE_GANG2

----------------------------------------------------------------------------------------------------------

**Primary job**: /sell drugs

----------------------------------------------------------------------------------------------------------

**Spray tag :** 

http://www.mediafire.com/file/y4cs0o5bweknd99/MMC_spray.dds.dds/file

----------------------------------------------------------------------------------------------------------
Safe disk's location and vehicles could be dealt in-game with me. 

Hopefully I did not forget anything.

**Comment by SAESKain** [comment]
Quality spawn codes

**Comment by Sira188** [comment]
Here we go

http://www.mediafire.com/file/g2s6xosfj24hoos/spawn_point.txt/file

**Comment by SAESKain** [comment]
No shader codes have been provided, you'll have no shaders unless you correct it before I'm done

**Comment by SAESKain** [comment]
Dunno how I didn't see that colour before, you're criminals not ALT. Fix it.

**Comment by SAESKain** [comment]
And just fix everything else that's probably inevitably broken.

Scorpyo was nice enough to fix your removeWorldModel table that was also broken here:
local removeWorldModels = {
	{13060,41.213638,360.51563,-97.23437,3.35156},
    {13064,41.213638,360.51563,-97.23437,3.35156},
    {1440,3.6364884,344.42368,-78.82397,1.14901},
    {1440,3.6364884,346.34293,-103.17119,1.07089},
    {3282,7.648582,341.19693,-62.18639,1.16718},
    {3282,7.648582,356.0759,-62.31395,0.77249},
    {3282,7.648582,366.7442,-63.19065,0.78009},
}

Re-request everything properly. Contact me on discord with your colour request instead.

BACK OF THE QUEUE.
