### ISSUE TITLE
VeC level 2 rewards

### ISSUE THREAD

**Issue by SAESHenry** [saesrpg/saesrpg-gang#124]
**<-- BASE FILES -->**
Mapping, object shaders can be found [here](https://mega.nz/#!4Q9X1CZS!Y6xOT_hQvMV-EN0yf44jWU2L3k-f-O_0CJJtbfwZqjI)

**<-- SPAWN -->**

```xml
<spawn id="Vandalos de El Corona" skin="109,298" x="1665.6999511719" y="-2133.3000488281" z="13.60" rot="287" weapons="1,1;22,75;25,50;28,150;46,1;41,4000" 
description="Violent latin street gang from the neighborhood of El Corona." r="51" g="153" b="102" restricted="gang,Vandalos_de_El_Corona" ganglevelrestriction="0" />
```

**<-- SKIN SHADER -->**

```lua
["Vandalos de El Corona"]={
	[109]={['fileName']='VEC1.dds',['textureName']='lsv2'},
},
```
    
[VEC1.dds](https://mega.nz/#!3mBGACwT!J_KFclwRDxPSpjfOpJC5sGfxYOoJkx19LTZx7l3UOa8)

**<-- SPRAY TAG -->**

```lua
["Vandalos de El Corona"]="images/VEC.dds",	
```
    
[VEC.dds](https://mega.nz/#!cMsxxAzY!WDVNea-N2th_5M7x3gB1ALQU6EJAPlWkBNTx_JfhTpg)

**<-- VEHICLES -->**

- Vehicles: Sabre / Bucanner / Savanna
- Primary color: #339966
- Upgrades : 10x nitro

**<-- EXTRA -->**

We would like to request:
- GR Safe ```xml <safe id="Vandalos de El Corona" x="1645.5" y="-2137.9" z="16.1" rot="60" restricted="gang,Vandalos_de_El_Corona" /> ```
- Drug selling ability.
- Ability to take part in bank robbery and turf wars.
- Our gang topic pinned on the forums.
- MOVE_GANG2 walking style.
- Safedisk

Thank you

**Comment by SAESKain** [comment]
Everything done except pending colour code and vehicles.

**Comment by SAESHenry** [comment]
Updated color code and skin shader
