### ISSUE TITLE
Mongols MC's Level 2 Rewards.

### ISSUE THREAD

**Issue by Sira188** [saesrpg/saesrpg-gang#126]
**Base mapping :**
http://www.mediafire.com/file/kl63vqhj6u4k72a/MMC-base.lua.lua/file
**Spawn point**

`<spawn id="Mongols MC" skin="100,248" x="346.5" y="-102.30000305176" z=" 1.4800000190735" rot="180" weapons="5,1;22,75;25,50;32,150;41,5000;46,1" description="For the law we are just a normal mechanics, but we are way more than that. We are doing everything we could do profit from. We are the Mongols Motorcycle. Mongols forever, forever Mongols" r="139" g="115" b="85" restricted="gang,Mongols_MC"/>`

**Base's shaders images **

http://www.mediafire.com/file/vsyoh51ci5uxlge/base_shaders.rar/file

**Base's shader code**
```
local shaders={
["images/brick.dds"]={"des_ntwnwall1",},
["images/logo.dds"]={"desbullsign",},
["images/flag.dds"]={"cjflag1",},
}
function setupShaders()
    for fileName,textures in pairs(shaders) do
        local shader = dxCreateShader ("shader.fx",1,100,false,"object")
        local texture = dxCreateTexture (fileName)
        dxSetShaderValue (shader,"CUSTOMTEX0", texture )
        shaders[fileName].shader=shader
    end
end
setupShaders()

-- code for object creation loop (assuming object is identified as "object"
for ,data in pairs(shaders) do
    local shader=data.shader
    for ,texture in pairs(data) do
        if type(texture)=="string" then
            engineApplyShaderToWorldTexture(shader,texture,object)
        end
    end
end
```
Base's location :

https://imgur.com/a/zXvmRjr

**Skin shader :

( skin id:100)**
http://www.mediafire.com/file/20lkryzgt79n7q8/skin_shader.dds.dds/file

Walking style
MOVE_GANG2

Primary job: /sell drugs

Spray tag :

http://www.mediafire.com/file/y4cs0o5bweknd99/MMC_spray.dds.dds/file

Safe disk's location and vehicles could be dealt in-game with me.

Hopefully I did not forget anything.

**Comment by SAESKain** [comment]
All sorted - pending colour code approval. Contact via discord

**Comment by Sira188** [comment]
The new spawn's codes with the new colour.

`<spawn id="Mongols MC" skin="100,248" x="346.5" y="-102.30000305176" z=" 1.4800000190735" rot="180" weapons="5,1;22,75;25,50;32,150;41,5000;46,1" description="For the law we are just a normal mechanics, but we are way more than that. We are doing everything we could do profit from. We are the Mongols Motorcycle. Mongols forever, forever Mongols" r="144" g="11" b="152" restricted="gang,Mongols_MC"/>`
