### ISSUE TITLE
OverdoseCrime Level 5 Rewards

### ISSUE THREAD

**Issue by Mrwann** [saesrpg/saesrpg-gang#128]
Hello there.

Walking Style:
MOVE_GANG1

Selling abilities:
Drugs / Weapons

Additions:
We have an ATM mapped In the base, we'd like It to work, and we also would love to have dual colts.

Exterior files:
https://www.mediafire.com/file/tq3hhs2p5gjafq2/Exterior.rar/file

ATM Coordinates:
posX="-1268.7" posY="2615.3999" posZ="108.3" rotX="0" rotY="0" rotZ="240"

Interiors & Shaders files:
https://www.mediafire.com/file/tv0py41nsstxw9f/Interior.rar/file

All the markers file:
https://www.mediafire.com/file/lhzmpecsnp1bk94/OCMARKERS.txt/file

Spawn:
https://www.mediafire.com/file/p1wte2jbdhr61yl/OCSPAWN.txt/file

The GR Safe code:
< safe id="OverdoseCrime" x="-1288.099609375" y="2619.900390625" z="115.69999694824" rot="0" restricted="gang,OverdoseCrime." />

Skin Shaders:

Skin name: Torino
Skin ID: 295
File: https://www.mediafire.com/file/tfl45iqs79fuyet/HQ_skin.dds/file

Skin name: somyri
Skin ID: 186
File: https://www.mediafire.com/file/8fguqakdyj5ob4a/Members_skin.dds/file

We'd like to add that we hope If you can fix the 2nd skin (girl skin) of us, Some people see It all black or all white and that's a bug I believe, Hope you can fix It too please.

I guess that's all, Thank you!

**Comment by SAESKain** [comment]
- Reducing the structure which gives access to the lift. This means leaving more distance between the entrance gate and the road (and making it assemble better if possible).
- Attempt to reduce the external wall of rock which is under the main building by approaching the most external rock objects to the mountain (if it's possible).(So it doesn't look that tall in vertical)

^ Notes from the new GM Henry/master

My notes:

Your gates are actually a joke, not one of them is correct. 
Fix them then resubmit.
