### ISSUE TITLE
Los Escondidos level 1 rewards

### ISSUE THREAD

**Issue by L1nkan** [saesrpg/saesrpg-gang#133]
Yo

If we are permitted to have one icon at our base now we would like to have one?

We would like one  Damaged Glendale and one Tahoma as the gang vehicles add nitro on both vehicles with color code: #a88f71

Place them here: https://i.imgur.com/hzLqdSJ.png (In the red box as shown in the picture)

Thanks // LE HQ Team

**Comment by SAESHenry** [comment]
Tahoma and hermes placed at LE base, payments done
