### ISSUE TITLE
Undisputed Command Level 1 Rewards

### ISSUE THREAD

**Issue by stayA9** [saesrpg/saesrpg-gang#134]
Hi, there as today we got accepted we would like to request our Rewards regarding Gang Vehicles.

---

GangPanel: Undisputed_Command

we would like to request a Picador color (6d4327) with NOS x10, Patriot the same color but with Hydraulics and NOS x10. Place them on the Central Command which is located above ALT's base, can be indicated in-game, Money for level acceptance can be given by Venom Douglas or Me (Stay)

---

**Comment by SAESHenry** [comment]
Vehicles and payments done
