### ISSUE TITLE
SWAT Forums Update

### ISSUE THREAD

**Issue by DROTDROT** [saesrpg/saesrpg-gang#139]
Hi,

Please form public subcategory with following within:
https://saesrpg.uk/topic/366/s-w-a-t-special-weapons-and-tactics?page=1
https://saesrpg.uk/topic/51/s-w-a-t-official-media-archive?page=1
Keep private SWAT forum intact.

Mod: https://saesrpg.uk/user/drot

**Comment by SScorpyo** [comment]
https://github.com/saesrpg/saesrpg-web
