### ISSUE TITLE
Rebels MC changes

### ISSUE THREAD

**Issue by jaspermta** [saesrpg/saesrpg-gang#142]
Good day GM team,

After a while of preparing ourself properly, we have now finished our rewards for level 3.
With these rewards, we will change our base as well.

If you have any questions, please feel free to contact me or another Rebels MC HQ.

# **Rebels MC exterior**
The mapped base exterior can be downloaded [here](https://mega.nz/#!scEgAKoQ!p2Vt-Yq4Q-H85xbZMswoSVysti1ip4XIG7Y7lk83-zU)

**Main gate**
`<trigger x="1048.7001953125" y="-321.900390625" z="74.699996948242" height="4.0" radius="8" movetime="2000" allowed="class,Rebels MC">
    <gate object="2938" pos="1048.7001953125,-321.900390625,74.699996948242,0,0,90" start="1048.7001953125,-321.900390625,74.699996948242,0,0,90" finish="1048.7001953125,-321.900390625,70.400001525879,0,0,90" />
</trigger>`

**Back gate**
`<trigger x="1049" y="-296.29998779297" z="74.699996948242" height="4.0" radius="8" movetime="2000" allowed="class,Rebels MC">
    <gate object="2938" pos="1049,-296.29998779297,74.699996948242,0,0,270" start="1049,-296.29998779297,74.699996948242,0,0,270" finish="1049,-296.29998779297,70.300003051758,0,0,270" />
</trigger>`

**Shaders**
Images of the shaders can be downloaded [here](https://mega.nz/#F!YEUUkQQB!tAVI-vsEDhGmpdgSVn9fkg)
and [here](https://mega.nz/#!gckGlSwD!YSxs-E5zxnPMFQFTsbfHQIaX0mk2rY0-3rhgfKwEPlQ)

**Spawn details**
`<spawn id="Rebels MC" skin="100,291" x="1013.7544555664" y="-309.93444824219" z="74" rot="270" weapons="5,1;41,5000;24,125;26,100;28,200;30,200;46,1" 
description="Faster than ever, as cruel as always! Rebels Motorcycle Club, we are the oldest, strongest and biggest Motorcycle Club of San Andreas" r="112" g="0" b="0" restricted="gang,Rebels-Motorcycle-Club" ganglevelrestriction="0" />`

**Spray tag**
Keep the spray tag the same as current.

**Shadered skin**
File of the shadered skin can be downloaded [here](https://mega.nz/#!QU1TjCrI!pY_Wsr3w9uRg0NHLDOhWVNZ8Tf9Ftu-P97xRTHibT7k)

The exact name of our spawn is "Rebels MC"
The model ID of the skin is 100.

# **Rebels MC interior**
The mapped base interior can be downloaded [here](https://mega.nz/#!QYMABCaB!5rFXqbBYOiooiCxxVSVRK9BcPs1GCvnZCCvewFm63VA)

**Markers**
`<interior restriction="" name="RebelsMCint">
    <entry pos="1031.34753, -306.68585, 73.99664" rotation="180" int="0" dim="0" />
    <exit pos="1020.0816040039,-346.98483276367,1143.23781826172" rotation="0" int="10" dim="0" />
</interior>
`

**Shader file interior**
The shader file for our interior can be downloaded [here](https://mega.nz/#!wV1HUQ4Y!kILh--NJpgMKsMZG3_Klb9f_OgqlJoITTX71cPRJq7M)

# **Gang vehicles**
Please meet Bas or another Rebels MC HQ in-game for the proper locations of our vehicles.
We (especially Bas) are kinda autistic regarding placements.

# **HQ Forums**
We would also like to have our HQ private forums added. 
https://saesrpg.uk/category/275/rebels

Please make the following users accessible
- https://saesrpg.uk/user/bas
- https://saesrpg.uk/user/bagetto
- https://saesrpg.uk/user/ferthis
- https://saesrpg.uk/user/swt
- https://saesrpg.uk/user/jasper

**Comment by SAESKain** [comment]
Your skinshader isn't a skinshader; it's a .txd file. Skinshaders should be no more than 65kb in a .dds format, thanks

**Comment by SAESKain** [comment]
And your interior file is just your shader codes

**Comment by Kare0015** [comment]
Hi Kain, thanks for addressing the mistakes we made. 

The interior file can be found [here](https://mega.nz/#!7eRDTAyC!-28Rtg9JmN_BdgoVFsmg7o0egId8UNkjb-1PNYQvVlA)

The skin can be found [here](https://mega.nz/#!LLZhDCzY!JlWuWBojUihKTGWAbOkmV_YdKpdwJ3HGFFeZNl-Jh-8)

Thanks in advance!
