### ISSUE TITLE
Comando Da Capital Skin change

### ISSUE THREAD

**Issue by Bizzle157** [saesrpg/saesrpg-gang#159]
Spawns

`<spawn id="Comando da Capital" skin="19,103,193" x="2472" y="-945" z="86" rot="90" weapons="10,1;24,250;27,250;28,350;31,450;34,150;16,10;46,1;41,5000"
description="A criminal faction fighting for peace justice and freedom" r="128" g="0" b="42" restricted="gang,Comando_da_Capital" ganglevelrestriction="0" />`

HQs Spawns

`<spawn id="Comando da Capital Direction" skin="98" x="2531" y="-964" z="88" rot="90" weapons="10,1;24,250;27,250;28,350;31,450;34,150;16,10;46,1;41,5000"
description="CDC HQ Spawn" r="128" g="0" b="42" restricted="gang,Comando_da_Capital" ganglevelrestriction="4" />`

Skin Shaders:

Skin 1 name: bmydj
Skin ID: 19
File: [https://mega.nz/#!DmQzkYRC!CQNglsM5yYi8jUPrlqpqM5-bG9VsURI-QEEWUvjJW7w](url)

Skin 2 name: ballas2
Skin ID: 103
File: [https://www.mediafire.com/view/8jn631tcjc2zodr/ballas1-Recovered-Recovered.png/file](url)

HQ skin: wmyri
Skin ID: 98
File:  [https://www.mediafire.com/view/b3ofvaqkrivhdsp/idk.png/file](url)

**Comment by SAESKain** [comment]
Your links are broken, re-request with actual links please.
