### ISSUE TITLE
SAFP changes request

### ISSUE THREAD

**Issue by safpscooter** [saesrpg/saesrpg-gang#16]
hello,
Where short in car's and we got to many unused chopper's so could 2 chopper's be removed from safp's rooftop and 2 buffalo's be added instead

2 out of 3 chopper's can be removed
https://i.imgur.com/iAcijW7.png

id like the buffalo's to be added here on the parkinglot
https://i.imgur.com/sU10jUP.png

Best regards, Scooter vL of SAFP

**Comment by nicusi** [comment]
I apologize you had to wait so freaking long, its sorted now.

**Comment by safpscooter** [comment]
@nicusi 
dont worry about it i understand yalll busy with 100 other things thank you mate!
