### ISSUE TITLE
S.W.A.T 2020 Requests

### ISSUE THREAD

**Issue by DenisIldis** [saesrpg/saesrpg-gang#160]
**SWAT 2020 Changes/Requests** 
_______________________________________________________________________________________________________________
**Spawns:**

Spawns code: https://pastebin.com/ymCyA8Pk
______________________________________________________________________________________________________

**Base & Base Shades:**

Base exterior file & Shaders included:http://www.mediafire.com/file/w6jqt161behkkrl/basseswat.lua/file (Fixed map: https://pastebin.com/g7Pf66T8)

**Base Shaders PNG's**: 

SWATwall : https://imgur.com/a/dVDg4yW

SWATlogo: https://imgur.com/a/SY1xaZy

______________________________________________________________________________________________________________

**Markers & Gates:**

Gates codes: https://pastebin.com/Wzy4CdN2

Markers codes: https://pastebin.com/K55ppxub

ATM: https://pastebin.com/5SrAGiuX

Peds/NPCs: https://pastebin.com/5ZmUta35

______________________________________________________________________________________________________________

**New Skin Shader & Vehicles coords :**

**Note:** This skin will be added to the current SWAT shaders as a third skin shader.

Skin name: swat
Skin ID: 285
File: http://www.mediafire.com/file/2xtom4pxjf5u1tx/crno1_%25281%2529.dds/file

 ['S.W.A.T. Officer']={
    [285]={['fileName']='crno1',['textureName']='swat'},
},

Vehicles: https://pastebin.com/nBuC3x8P
______________________________________________________________________________________________________

**Note:** We're keeping the current interior as for now.

______________________________________________________________________________________________________

Thanks in advance!

**Comment by DROTDROT** [comment]
**Fix:**

**Spawns:**
https://pastebin.com/z4PnT5Fk

**Gates:**
https://pastebin.com/Pc348NAa
