### ISSUE TITLE
Bloodz - Level 2 Rewards Request

### ISSUE THREAD

**Issue by AlyosHyper** [saesrpg/saesrpg-gang#164]
Hello, we would like to request level 2 rewards.

**<-- SPAWN -->**

`<spawn id="BloodZ" skin="102,19" x="226.06616" y="-1406.26831" z="51.65625" rot="225" weapons="1,1;22,75;25,50;28,150;46,1;41,5000" 
description="BloodZ, street gang based in Los Santos that is involved in drugs, theft and murder, among other criminal activities." r="194" g="0" b="0" restricted="gang,BloodZ_" ganglevelrestriction="0" />`

**NOTE:** I'm not sure if the spawn rotation is set to right degree, if it's not please fix it so the character will face the exit doors. Thanks.

**<-- GANG BASE -->**

**Address:** Richman Love Cabin

http://www.mediafire.com/file/1gfhlob4a29yj4t/BloodzTripleOGBase.lua/file

**<-- SKIN SHADER -->**

`['BloodZ']={
    [102]={['fileName']='bloodz1.dds',['textureName']='ballas1'},
}, `

http://www.mediafire.com/file/ka145724uvz5lgl/bloodz1.dds/file

**<-- SPRAY TAG -->**

`["BloodZ"]="images/bspray.dds",`

http://www.mediafire.com/file/5buvsym7khjj65c/bspray.dds/file

**<-- VEHICLES -->**

- Savanna, Stratum, Damaged Glendale, Sultan, Maverick
- Primary Color: #C20000
- Secondary Color: #C20000
- Upgrades: 10x Nitro

**<-- EXTRA -->**

- Ability to sell drugs.
- Ability to take a part in bank robberies and turf wars.
- Our gang topic pinned on the forums.
- MOVE_GANG1 walking style.

**Comment by SAESKain** [comment]
Don't use Ikzelf's map converter, it's broken.

Convert your map properly using Nanos.

**Comment by AlyosHyper** [comment]
The base has been converted with Nanobob's converter. Thanks.
