### ISSUE TITLE
The Company Requests

### ISSUE THREAD

**Issue by adistarsaes** [saesrpg/saesrpg-gang#168]
Everything can be found in this file:

https://drive.google.com/open?id=14OTvkIv42CHEagyAJsNmFqg_1ng4QyIq

Also please make all our interiors PUBLIC.

**Comment by SAESKain** [comment]
THC2 shader exceeds the limits, you can find the limit guidance here: https://saesrpg.uk/topic/5633/shader-size-limits

**Comment by SScorpyo** [comment]
[THC2.dds](https://mega.nz/#!QVl0UaxB!0t6yCnR9wGtgHfIMQ3eS7AuFnSfp8qW_h9aq_gMTenk)

**Comment by Mohamedelh** [comment]
> [THC2.dds](https://mega.nz/#!QVl0UaxB!0t6yCnR9wGtgHfIMQ3eS7AuFnSfp8qW_h9aq_gMTenk)

We confirm that this is the new dds file. The rest can be find in my zip file(no access to pc rn)

**Comment by SAESKain** [comment]
Feedback provided via discord.

Badly textured armpits on skins 216 and 126. Other than that they look really good.
