### ISSUE TITLE
Arms Assassins Skin Shader + base marker 

### ISSUE THREAD

**Issue by JoaoCanelas** [saesrpg/saesrpg-gang#170]
Hey there, we're changing the skin shaders on one spawn, for 2 of the 3 skins available. Details below.

Spawn name: Arms Assassins
Skin name: hmyri
Skin ID: 46
Skin shader: https://cdn.discordapp.com/attachments/301379194221232136/668429704356823040/HMYRI.dds

Spawn name: Arms Assassins
Skin name: wmyammo
Skin ID: 179
Skin shader: https://cdn.discordapp.com/attachments/301379194221232136/668429702964445207/WMYAMMO.dds

Also we're adding a new marker to our base, from top deck to bottom. Here's the code for it:

```
<interior restriction="class,Arms Assassins,Arms Assassins Novice" name="AATopToBottomDeck" >
    <entry pos="-2465.81640625,1559.2137451172,17.593982696533" rotation="270" int="0" dim="0" />
    <exit pos="-2440.8430175781,1550.2858886719,2.1171875" rotation="270" int="0" dim="0" />
</interior>
```
Last thing, we'd like to **increment** the elevator ('AA elevator' from base, we only have one) trigger radius with '1'.

Any question or issue please do reply here and I'll provide or change anything required.

Thanks,
Canelas, AA Leader.

**Comment by SAESKain** [comment]
```
<interior restriction="class,Arms Assassins,Arms Assassins Novice,Admin" name="AATopToBottomDeck" >
        <entry pos="-2465.81640625,1559.2137451172,16.7" rotation="270" int="0" dim="0" />
        <exit pos="-2440.8430175781,1550.2858886719,2.1171875" rotation="270" int="0" dim="0" />
    </interior>
```

Better marker coords ^ Needs a door adding though to look realistic.
