### ISSUE TITLE
Cartel De Sinaloa |Level 1 Rewards

### ISSUE THREAD

**Issue by Escobar82** [saesrpg/saesrpg-gang#183]
Hi everyone!
Cartel De Sinaloa has obtained level 1 which we would like to request our rewards:

2 gang vehicles -
1-stratum
2-Hotring Racer 3
Color 1: # 635437
Improvements: Nitroso x10

Our base:
https://imgur.com/E62qQvP

Position of the Cars:
https://imgur.com/XEntgdS

A Private Role Group Called "Cartel De Sinaloa" and a Deputy Private Forum.

The Group Administrators will be
https://saesrpg.uk/user/audi
https://saesrpg.uk/user/zach7
https://saesrpg.uk/user/evozz

We would like our Media Archive and Main Theme to be transferred. Where they are in the Gang Subcategories section, to Our private forum.
https://saesrpg.uk/topic/14329/cartel-de-sinaloa-level-1?page=1
https://saesrpg.uk/topic/14287/cartel-de-sinaloa-media-archive?page=1

**Comment by Ahren7413** [comment]
The in-game rewards (vehicles) was sorted. Regarding the forum's group it needs to be requested in a different category which is: https://github.com/saesrpg/saesrpg-web/issues
