### ISSUE TITLE
Los Inkas Level 1 Rewards

### ISSUE THREAD

**Issue by Broken-RadiO** [saesrpg/saesrpg-gang#184]
Hello there,

We would like to request a public subforum within the 'gangs' section with a few subcategories which can be found below.
Forums Name: Los Inkas
Forums logo: https://imgur.com/a/dnmSGyW
Forums Color Code: 4A092B
Forum Moderators:
- RadiO ( https://saesrpg.uk/user/radio )
- Chafloque ( https://saesrpg.uk/user/chafloque )

And we like to move our main topic and our media archive into this public subforums.
- Los Inkas Main Topic: https://saesrpg.uk/topic/14048/los-inkas
- Los Inkas Media Archive: https://saesrpg.uk/topic/14049/los-inkas-media-archive

As well we would like to request a forums tag.
Forums Tag: ♛ Los INKAS 
Forums Tag Color: 4A092B
Moderators:
- RadiO ( https://saesrpg.uk/user/radio )
- Chafloque ( https://saesrpg.uk/user/chafloque )
- Spartan ( https://saesrpg.uk/user/spartan )
- Huaynito ( https://saesrpg.uk/user/huaynito )
- hedi010 (Aurora) ( https://saesrpg.uk/user/hedi010 )

A discord channel for Los Inkas HQs in SAES Gang Management discord.
Channel Name; Los Inkas
Role Color: 4A092B

The two vehicles and the location will be shown ingame. 
Thanks in advance!

On behalf of Los Inkas HQ Team,
Los Inkas Imperial Consul,
RadioGaga.

**Comment by Ahren7413** [comment]
The in-game rewards were sorted. However the forums rewards must be requested in a different git category, which is: https://github.com/saesrpg/saesrpg-web/issues .
