### ISSUE TITLE
Gypsy Jokers MC - Level 1 Rewards

### ISSUE THREAD

**Issue by turbo06** [saesrpg/saesrpg-gang#185]
Hello **gentlemen,**
We would like to request the following things below:

 **Forums tag**
- Tag name: (Skull icon) Gypsy Jokers MC 
- Tag colour: #363636
- Moderators:
https://saesrpg.uk/user/turbo
https://saesrpg.uk/user/darude
https://saesrpg.uk/user/premier

 **Sub forums**
- Topics within the subforums:
https://saesrpg.uk/topic/14516/gypsy-jokers-mc-level-1/1
https://saesrpg.uk/topic/14520/gypsy-jokers-mc-media-archive
- Subforum moderators:
https://saesrpg.uk/user/turbo
https://saesrpg.uk/user/darude
https://saesrpg.uk/user/premier

 **Vehicles**
- 2 freeways (additions will be explained in-game)

Those were our requests, thanks in advance.
On behalf of the Gypsy Jokers MC - HQ Team,
Turbo

**Comment by DROTDROT** [comment]
Vehicles and level/vehicles fee sorted. Unclear if mod rights and topics were given already. 
If not, request here: https://github.com/saesrpg/saesrpg-web/issues
