### ISSUE TITLE
Medellin Cartel - Level 1 Rewards

### ISSUE THREAD

**Issue by WenDo21** [saesrpg/saesrpg-gang#187]
Hello dear Gang Management,

I would like to claim the **Level 1** **rewards** for the gang **Medellin Cartel**.

**Vehicles:** 
The two vehicles will be:
Sultan and Glendale
Color: #9b6c62
Locked to gang: Medellin
Location of the base: https://i.imgur.com/0TH1gUN.png 
Location of the vehicles: https://i.imgur.com/SqkBMOb.png 

**Forum Tag:**
Name: Medellin Cartel
Color: #9b6c62
Moderators: 
https://saesrpg.uk/user/wendo
https://saesrpg.uk/user/marksman
https://saesrpg.uk/user/kim

**Discord Channel in GM’s Discord**
Name: Medellin Cartel
Role Color: #9b6c62

A private forum named “Medellin Cartel”.

Also, we would like to have our topic and media archive in the **private forums.
https://saesrpg.uk/topic/14142/medellin-cartel-level-1** 
https://saesrpg.uk/topic/14143/medellin-cartel-media-archive

**The admins of the forum:**
https://saesrpg.uk/user/wendo
https://saesrpg.uk/user/marksman
https://saesrpg.uk/user/kim

Yours Sincerely,
**Medellin HQ**

**Comment by Ahren7413** [comment]
The in-game rewards were sorted. However the forums rewards must be requested in a different git category, which is: https://github.com/saesrpg/saesrpg-web/issues .
