### ISSUE TITLE
Rogue 21 - Level 1 Rewards

### ISSUE THREAD

**Issue by CrankYou** [saesrpg/saesrpg-gang#188]
Oi fellas,
we would like to request the following things below:

**Vehicles**

1. Name: Securicar, ID: 428 (If possible)
2. Name: Patriot, ID: 470
BOTH with the colour: #212D1C
Replace the Securicar with another Patriot IF it is not allowed to request as a gang vehicle.

Location: Infront of our gang base (https://cdn.discordapp.com/attachments/317991079347617793/684523610362347529/a1.png)
^Locked to Rogue 21

If you have any questions left, please ask us on the SAES Gang Management Discord.
With kind regards,

Crank
&
_High-Command of Rogue 21_

**Comment by DROTDROT** [comment]
Vehicles added, level & vehicle fees paid, sorted.
