### ISSUE TITLE
Tuga thugs dual colt

### ISSUE THREAD

**Issue by GrooveOG** [saesrpg/saesrpg-gang#189]
mr licano pls dual pew pew on "Tuga Thugs" and "Tuga Thugs Novato"

**Comment by GrooveOG** [comment]
dual pew pew ability **** not physically added to the spawn

**Comment by GrooveOG** [comment]
@SAESKain HELLO LORDS AND SAVIOURS OF THIS POOR PLANET AND US PEASANTS, WE, TT, WOULD LIKE TO HAVE DOUBLE BUMBAMS WITHOUT LOSING DESERT EAGLE.
THANKS YOU IN ADVANCE, YOURS PEASANT 

no new colt on spawn ok

**Comment by Ahren7413** [comment]
👍
