### ISSUE TITLE
Cunning Stunts (CS)- Changes/Requests

### ISSUE THREAD

**Issue by DenisIldis** [saesrpg/saesrpg-gang#19]
**Cunning Stunts 2019 Changes/Requests** 
_______________________________________________________________________________________________________________
**Spawns & Mechanic Ability:**

**(Mechanic ability added to all of the spawns expect the Cunning Stunts Drifter/Civilian Spawn)** 

Spawns code: https://pastebin.com/q2M3VB0z

**Cunning Stunts Drifter (Civilian spawn)**- Moved to the new base.
_______________________________________________________________________________________________________________

**Skins Shaders:**

Spawn name: Cunning Stunts HQ
Skin name: bmycr
Skin id: 21
Model: https://www.mediafire.com/view/1ccm6ubk9lcbk5m/hU6ze87.jpg/file

Spawn name: Cunning Stunts Member
Skin name: bmytatt
Skin id: 180
Model: https://www.mediafire.com/view/taqbwwwcbm1coi7/CSSHADER.png/file

Spawn name: Cunning Stunts Rookie
Skin name: wmydrug
Skin id: 29
Model: https://www.mediafire.com/view/n5f1jwdfi9yydze/csskin.png/file

______________________________________________________________________________________________________________

**Base & Base Shades:**

Base files/mapping/Base shaders code/Base Shades: Base shaders code: https://files.fm/u/z3xj3cv9#/
______________________________________________________________________________________________________________

**Gates:**

Gates codes: https://pastebin.com/ryFg1vwY

______________________________________________________________________________________________________________

**Comment by nicusi** [comment]
It shows that files got expired & deleted, could you re-upload?

**Comment by DenisIldis** [comment]
@nicusi Fixed.

**Comment by ghost** [comment]
Base is missing the genereated LUA file @TheRealElement

**Comment by RealCarter** [comment]
http://www.mediafire.com/folder/98bjm7urfb6rmsg,ucgqcpn3ntaeumg,jewb53rtajm9zem/shared

@saesikz
