### ISSUE TITLE
Organization Zero-Level 5 Rewards

### ISSUE THREAD

**Issue by FugiTheGoat** [saesrpg/saesrpg-gang#190]
Hello.

To begin with I'd like to request the removal of the shader that we used for our Omyri, ID:59 skin at Organization Zero spawn. We want the original one, non-shadered.

Weapons for both Organization Zero and Organization Zero Nobility spawns:

-250 Dual Colt
-250 Combat Shotgun
-350 MP5
-450 M4
-150 Sniper
-10 Grenades
-5000 Spraycan
-Parachute
-Pimp Cane as Melee

Secondary job/selling ability: Drugsale

Thank you in advance,
Organization Zero HQ Team.

**Comment by DROTDROT** [comment]
https://saesrpg.uk/topic/3698/how-to-request-rewards-create-spawns-gates-markers-mappings-shaders

**Comment by Ahren7413** [comment]
Missing second job ability, it will be handled by @SAESKain 

Besides that, the rest is good to go.
