### ISSUE TITLE
SAFP Spawn changes request #2

### ISSUE THREAD

**Issue by MTA-Shadro** [saesrpg/saesrpg-gang#191]
Hello again,
We would like to change some of our skins and shaders, here is how it goes:
Remove the 3rd shadered skin in SAFP officer spawn (the blue agent), replace it with a non-shadered female officer. Also, add a shader for the female officer skin in SAFP Marshal spawn. That means we'll have two female officer skins: without a shader for officers, with a shader for Marshals. Finally, Replace the 3rd skin in the Marshal spawn (Default grey-suited Asian skin) with Toreno's skin.

Details: (4/4 skins ; 4/4 shaders)
-SAFP Officer:

1) LSPD officer with a shader (Model: lapd1 ; ID: 280) - In use.
2) SWAT officer with a shader (Model: swat ; ID: 285) - In use.
3) Female officer without a shader (Server's custom skin) - Not used for this spawn, we want it to be added instead of the Asian agent with the blue shader.

-SAFP Marshal:

1) Female officer with a shader - In use but without a shader, we would like the following shader to get tested first (please provide screenshots) then added to the server: https://imgur.com/0yPsPFT
2) SWAT officer with a shader (Model: swat ; ID: 285) - In use.
3) Mike Toreno without a shader (Model: torino ; ID: 295) - We want to bring this skin back as a replacement for the not shadered grey-suited Asian guy (Model: somyri ; ID: 186) that we have now as a 3rd spawn for SAFP Marshal.

Kind regards,
Shadro, Commissioner of the S.A. Federal Police.

**Comment by Ahren7413** [comment]
Please follow this guide: https://saesrpg.uk/topic/3698/how-to-request-rewards-create-spawns-gates-markers-mappings-shaders in order to do the request
