### ISSUE TITLE
Black~Bullets Changes

### ISSUE THREAD

**Issue by iMatizZ** [saesrpg/saesrpg-gang#192]
Hello ! We would like to make one forums with our official topic, media archive & private forum in on section like others do ! Will be ez for everyone ;) 
Official topic: https://saesrpg.uk/topic/332/black-bullets?page=1
Media archive: https://saesrpg.uk/topic/582/black-bullets-media-archive?page=1
Moderators:
ESO : https://saesrpg.uk/user/eso  (i think he has rights as admin)
RAMPAGE : https://saesrpg.uk/user/rampage  (i think he has rights as admin)
A7md : https://saesrpg.uk/user/a7md
Me : https://saesrpg.uk/user/matizz
Honer: https://saesrpg.uk/user/honer112
Style : https://saesrpg.uk/user/style

You can check group forums here: https://saesrpg.uk/groups/black-bullets or ESO can approve it , if you need it .

Last one we want change our doulbe **colts** back to **deagle** on both spawns . Thanks

**Comment by Ahren7413** [comment]
Hi friend. Sadly we cannot take care of that since only HQs has access to forum changes. Instead please post your request in here: https://github.com/saesrpg/saesrpg-web/issues
