### ISSUE TITLE
CripZ Gang Changes

### ISSUE THREAD

**Issue by AdemBygt** [saesrpg/saesrpg-gang#193]
Hello.

We would like to add Delivery Man job to CripZ spawn.

**Comment by ZazaBast** [comment]
Hey its zaza, we would like to remove Alcohol selling ability from both spawn CripZ and CripZ OG and adding delivery man job to our both spawn if its possible .

**Comment by AdemBygt** [comment]
We would like to add Transporter Job to CripZ spawn.

You can remove   Alcohol selling ability from both spawn CripZ and CripZ OG and

Code For Peds.

367.05349731445,-2092.1772460938,7.8338875770569

**Comment by Ahren7413** [comment]
Sorted.
