### ISSUE TITLE
FBI Changes

### ISSUE THREAD

**Issue by IEDaryl** [saesrpg/saesrpg-gang#194]
HELLO

New changes, old request.

Base: https://discordapp.com/channels/679395223016833024/679408450295300104/692851964878520320

Gates; https://discordapp.com/channels/679395223016833024/679408450295300104/692852199549566997

Markers;
https://discordapp.com/channels/679395223016833024/679408450295300104/692853404153937950

RPGskinShader client side:
https://discordapp.com/channels/679395223016833024/679408450295300104/692857097968287765

RPGskinShader meta:
https://discordapp.com/channels/679395223016833024/679408450295300104/692857376700629063

RPGskinShader images:
https://discordapp.com/channels/679395223016833024/679408450295300104/692857698362064896

RPGspawnmaps -> sanfierro.map :
https://discordapp.com/channels/679395223016833024/679408450295300104/692858029221085234

**Comment by Ahren7413** [comment]
👍 Waiting to be pushed.

**Comment by DROTDROT** [comment]
2nd set of changes sorted (post-edit), to be pushed.
