### ISSUE TITLE
SAFP Marshals Level Restriction Change

### ISSUE THREAD

**Issue by wizax49** [saesrpg/saesrpg-gang#196]
Dear SAES Web Managers,

As I am the new SAFP Leader I'd like to request some small updates on the Marshals level restriction to the following: 

<spawn id="SA Federal Police Marshal" skin="265,285,186" x="1484.6" y="2843.2" z="10.1" rot="0" weapons="3,1;41,2500;23,200;27,150;29,450;31,450;34,150;44,1;17,10" 
        description="SA Federal Police Marshals is a task force created to find and bust wanted fugitives, transport dangerous federal prisoners and provide witness protection." r="0" g="75" b="152" restricted="squad,San_Andreas_Federal_Police"ganglevelrestriction="3"/>

Thanks in advance;
Commissioner Wizax,
San Andreas Federal Police.

**Comment by Ahren7413** [comment]
Will be live in the next update.
