### ISSUE TITLE
Peaky~Blinders- Level 2- Rewards Request

### ISSUE THREAD

**Issue by LuciferSAES** [saesrpg/saesrpg-gang#197]
Hello Everyone,

I would like to request the Peaky Blinders Base in Las Venturas: 
Mapping .lua + Shaders : https://dosya.co/9jm7gaijxy1p/pb-files.rar.html
Skin Shaders : https://dosya.co/h20jfydvzcxq/bmypimp_1.dds.html

Spawn Format : 
 < spawn id="Peaky Blinders" skin="249,169" x="1869.5" y="1288" z="58.90000" rot="90" weapons="1,1;22,75;25,50;28,150;46,1" 
description="An old Family Gang that was born in Birmingham and now moved to San Andreas to take control!" r="82" g="61" b="58" restricted="gang,Peaky-Blinders" ganglevelrestriction="0" />

(Due to some unknown issues on github the text above didn't wanted to appear, so i added a space between ''<'' and ''spawn'' you may remove it, thank you) 

Markers Format : 

     <interior name="PB1">
        <entry pos="1906.47461,1298.75208,54.37308" rotation="270" int="0" dim="0" />
        <exit pos="1952.0999755859,1343,14.500000381" rotation="90" int="0" dim="0" />
    </interior>

     <interior name="PB2">
        <entry pos="1886.06250,1423.86890,71.70684" rotation="90" int="0" dim="0" />
        <exit pos="1873.28247,1408.75464,15.600" rotation="180" int="0" dim="0" />
    </interior>

     <interior name="PB3">
        <entry pos="1857.6999511719,1366.5999755859,15.600" rotation="0" int="0" dim="0" />
        <exit pos="1861.6999511719,1362.9000244141,54.5" rotation="180" int="0" dim="0" />
    </interior>

Weapons:  (Bat, 75 Colt-45, 50 Shotgun, 150 Mini-Uzi, Parachute).

Primary job : /sell (drugs)

Color Code: #523D3A

Vehicules: Dodo, Picador, Admiral (Car's position will be given in game at the Peaky Blinders Casino) 

Spray Tag Picture: https://media.discordapp.net/attachments/597612493505822730/695456605025599518/Peaky_Blinders_Spray_Tag.png

Gang mini-map blip on base location: x: 1931.903,1362.457,9.250

Save disk on base location  : x: 1934.58 y: 1396.34 z: 9.25

Best Regards
[P~B]Lucifer 
Peaky Blinders Vice Leader

**Comment by DROTDROT** [comment]
Vehicles added (dodo, picador, admiral).
Vehicle + level fees collected (14m).
Disk added.
Property icon converted to "gang":
(rental property - https://saesrpg.uk/topic/15763/tombaa-peaky-blinders-the-high-roller-casino)

**Comment by Ahren7413** [comment]
Ready to be pushed.
