### ISSUE TITLE
Navy Malistrip ~ Level 1 rewards

### ISSUE THREAD

**Issue by bazuka36** [saesrpg/saesrpg-gang#198]
Hello, those will be the request we will do as Navy Malistrip

Vehicle part: 
**Note:** we would like to have all vehicles to have the our color code which is #678b78
We would like to have a **Tropic** located at pirate spawn like this:
https://media.discordapp.net/attachments/677649751973429248/695600405580873739/unknown.png
And a **picador**:
https://media.discordapp.net/attachments/677649751973429248/695600895358009344/unknown.png

__

We also would like to request a private forum.
Forum mods
Siper: https://saesrpg.uk/user/siper_
Bazuka: https://saesrpg.uk/user/bazuka36
xDarkman: https://saesrpg.uk/user/xdarkman
Group name: Navy Malistrip

Logo: https://i.ibb.co/8Mk5PYc/logo.png
Group color: #678b78

___

Thank you beforehand!

**Comment by Ahren7413** [comment]
Hi @bazuka36 . Please refer to the forums request to this section: https://github.com/saesrpg/saesrpg-web/issues

**Comment by Ahren7413** [comment]
Everything in here was sorted.
