### ISSUE TITLE
B~B Spawn changes

### ISSUE THREAD

**Issue by iMatizZ** [saesrpg/saesrpg-gang#201]
Hey there ! We would like rename our spawn =>` Black~Bullets HQ to Black~Bullets Veteran` restrict level 3+ ,  color same : #ff4500 as normal spawn one. Thanks ! 

EDIT: We have requested to change our double colts to **deagle** , still waiting so i ll just leave a link here since you closed it
https://github.com/saesrpg/saesrpg-gang/issues/192

**Comment by iMatizZ** [comment]
Ah totally forgot about gates, markers, sell, gun running etc might  need an update after the name change .

**Comment by Ahren7413** [comment]
Sorted.

**Comment by elyeso4** [comment]
when is this going live ?
