### ISSUE TITLE
O new base

### ISSUE THREAD

**Issue by SAES-Jay** [saesrpg/saesrpg-gang#205]
Can Lican'to or THOT message me on Discordia for the base files :)))))))))))

New spawn codes
`
            <spawn id="The Outfit" skin="98,120,233" x="-688.045" y="946.247" z="13.031" rot="0" weapons="2,1;41,5000;22,250;27,250;32,350;30,450;34,150;16,10;46,1" 
            description="An organised English crime family who specialise in import and export." r="105" g="105" b="105" restricted="gang,The_Outfit" ganglevelrestriction="0" />
            <spawn id="The Outfit Lynchpin" skin="186" x="-688.045" y="946.247" z="13.031" rot="0" weapons="2,1;41,5000;24,250;27,250;32,350;30,450;34,150;16,10;46,1" 
            description="The Lynchpin of an organised English crime family who specialise in import and export." r="105" g="105" b="105" restricted="gang,The_Outfit" ganglevelrestriction="4" />
`

Markers
```
<!-- Outfit  -->
    <interior restriction="class,Admin,Staff,The Outfit,The Outfit Lynchpin" name="Obalcony">
        <entry pos="-692.0615234375,939.49432373047,13.6328125" rotation="90" int="0" dim="0" />
        <exit pos="-693.43658447266,937.4580078125,16.828125" rotation="90" int="0" dim="0" />
    </interior>
     
    <interior name="Ointerior">
        <entry pos="-683.04888916016,937.18719482422,16.828125" rotation="270" int="0" dim="0" />
        <exit pos="-669,970,2996" rotation="90" int="5" dim="5" />
    </interior>
     
```

**Comment by Ahren7413** [comment]
👍

**Comment by Ahren7413** [comment]
👍

**Comment by SAES-Jay** [comment]
Danke

New ATM location for Kain(?) to add
x -682.49407958984
y 944.38031005859
z 12.1328125
r 0
