### ISSUE TITLE
C small change

### ISSUE THREAD

**Issue by Jesse421** [saesrpg/saesrpg-gang#206]
hello there,
we'd like to change our second spawn level restriction from 3 to 7
here is the correct code:
<spawn  id=“Clandestine Mob Consiglio” skin=“127”  x="-1183"   y="-1156.9"   z="135.6"   rot="0" weapons=“1,1;24,175;27,200;29,300;31,350;34,100;41,6000;46,1” description=“The members of Clandestine Mob Council” r=“105” g=“82” b=“6”  restricted=“gang.Clandestine_Mob” ganglevelrestriction="7"/>

**Comment by Ahren7413** [comment]
👍
