### ISSUE TITLE
Medellin - Level 2 Rewards

### ISSUE THREAD

**Issue by WenDo21** [saesrpg/saesrpg-gang#207]
Hello Everyone,
As Medellin has reached the level 2, we would like to request the rewards.

<<< BASICS >>>
Spawn: https://pastebin.com/zWtzvHsk 
Marker: https://pastebin.com/QUChiCAc
Base: https://ufile.io/67hlmt2g
Ability: Drug selling
Walking Style: MOVE_GANG1

Disk: -1868.118,-128.973,11.894
Blip:  -1868.126,-178.259,9.341

<<< SKIN SHADER >>>
Skin Shaders: https://ufile.io/kw50pie9 
["Medellin Cartel"]={[124]={["fileName"]=m-shader.dds',["textureName"]="vmaff1"},},

<<< SPRAY TAG >>>
Spray Tag: https://ufile.io/jfhwaqfi 
["Medellin Cartel"]="images/m-spray.dds",

<<< VEHICLES >>>
2 x Admiral - #9b6c62
1 x Huntley - #9b6c62

<<< PROPERTIES / ICONS >>>
Remove: Medellin Cartel Is Better Than Tt & Hideout De Medellin Cartel
Add:  Medellin HQ

Thanks in advance!

**Comment by Ahren7413** [comment]
👍
