### ISSUE TITLE
Gypsy Jokers MC - Level 2 Rewards

### ISSUE THREAD

**Issue by turbo06** [saesrpg/saesrpg-gang#209]
Hello gentlemen,

I would like to request the level 2 rewards of GJMC

**Mapping .lua :** https://ufile.io/vicq52yl
**Mapping Shaders + images :** https://ufile.io/ir73gkdg + https://ufile.io/ww4ili3b
**Skin Shader :** https://ufile.io/wwr4cocg

**Spawn Format:**
< spawn id="Gypsy Jokers MC" skin="181,248" x="2134.9860839844" y="-2276.78515625" z="20.671875" rot="315" weapons="5,1;22,75;25,50;28,150;46,1;41,4000" 
description="We ride fast, work slow and never rush!" r="54" g="54" b="54" restricted="gang,Gypsy_Jokers_MC" ganglevelrestriction="0" />

**Markers Format:**
< interior name="GJMCheli">
    < entry pos="2142.18628 -2293.35889 20.67596" rotation="226" int="0" dim="0" />
    < exit pos="2139.77319 -2291.05859 20.67188" rotation="40" int="0" dim="0" />
< /interior>

**Primary Job:** 
/sell (arms)

**Color Code:** 
#363636

**Vehicles:** 
Helicopter, Freeway, Buritto 

**Spray Tag Picture:** https://cdn.discordapp.com/attachments/700772625491951628/704852846079770694/gypsy.png

Thanks in advance,
Turbo

**Comment by L1nkan** [comment]
Spray Tage Image needs to be DDS file too. Here u go 
https://www.mediafire.com/view/wz5evxz5wfoznqo/gypsy.dds/file
