### ISSUE TITLE
Hell Raisers MC Level 1 Rewards

### ISSUE THREAD

**Issue by Franklin880** [saesrpg/saesrpg-gang#21]
Hello there, HRMC got accepted for level 1 recently, and we want to request the following rewards:

2 Gang Freeways at our base, colored #473131, available to everyone that is in the HellRaisersMC /gang panel

Location of the Freeways: https://cdn.discordapp.com/attachments/521022168075730945/541247880187346950/mta-screen_2019-02-02_14-24-03.png

Location of the base:
https://cdn.discordapp.com/attachments/530052805147230218/530121204355432468/unknown.png

**VEHICLES SORTED!**

Also, private forums/group for our gang.

Group color: 473131
People that should be added to the forum group: Franklin reket Polentaa Gurdman Sajjad HardBass Crystal Facecontrol Crippin xTension Pixelator

^Their forum names

Moderators of the group: Franklin, reket

**Comment by MrMedEra** [comment]
@Franklin880 add the account of people that shall be added to moderation on private forums this may help in sorting

**Comment by Franklin880** [comment]
> @Franklin880 add the account of people that shall be added to moderation on private forums this may help in sorting

It's a gang freeway tho?

**Comment by Franklin880** [comment]
Fixed it.. thanks @FilexGH

**Comment by Heshalicious** [comment]
Vehicles sorted.

**Comment by ghost** [comment]
Forum group created you can add people yourself @Franklin880 
only thing left for you is to provide a list of moderators for the private forum

**Comment by Franklin880** [comment]
> Forum group created you can add people yourself @Franklin880
> only thing left for you is to provide a list of moderators for the private forum

Franklin & reket

**Comment by ghost** [comment]
solved and locked
