### ISSUE TITLE
Texas Rangers - Level 1 Rewards

### ISSUE THREAD

**Issue by Bozi07** [saesrpg/saesrpg-gang#211]
Hi. We would like to request our level 1 reward.

Vehicle part: 
2x Police Sultans parked at our base in BC @ Fort Carson, upgraded like the sultan which is already donated there. 

---
We would like to request a private forum:
Forum moderators:
Laza: https://saesrpg.uk/user/laza
Bozi: https://saesrpg.uk/user/bozi
Bones: https://saesrpg.uk/user/bones

Squad name: Texas Rangers

Logo: https://i.imgur.com/qrmmtTg.png
Squad color: #a6a1fd

**Comment by Ahren7413** [comment]
👍
