### ISSUE TITLE
Los INKAS - Level 2 Rewards

### ISSUE THREAD

**Issue by Chafloque** [saesrpg/saesrpg-gang#215]
### Spawn:

`<spawn id="Los Inkas" skin="293,104" x="1020" y="-57.900001525879" z="26.39999961853" rot="188.997940" weapons="1,1;10,1;22,75;25,50;28,150;46,1;41,4000" description="INKAS, more than a word is a way of acting, a tribute to the empire that once reigned over Latin America, in addition to the terrorist group that dominated Peru during the 90s." r="74" g="9" b="43" restricted="gang,Los_INKAS" ganglevelrestriction="0" />`

### Base Mapping
http://www.mediafire.com/file/f3031o66z7deeyc/INKAS_New_Base.rar/file
Fixed .lua file : https://www.mediafire.com/file/lbe6ghkv1bl8sv2/INKAS.lua/file

### Skin Shader:
`["Los Inkas"]={[293]={["fileName"]=inkas-skin.dds',["textureName"]="ogloc"},},`
http://www.mediafire.com/file/n44s2mkx60zvazc/inkas-skin_%25284%2529.dds/file

### Spray Tag:
`["Los Inkas"]="images/inkas-spray.dds"`
http://www.mediafire.com/file/0pjk0ol9yjab32i/inkas-spray_%25281%2529.dds/file

### Primary Job:
/sell (drugs)

**Walking style:** MOVE_GANG1

Safe disk's location and vehicles could be dealt with in-game.

### Color Code:
#4A092B

**Ability to take part in bank robbery and turf wars.**

Thanks in advance.
Chafloque

**Comment by L1nkan** [comment]
Lua file was fucked and few objects had no colision. Fixed file here : https://www.mediafire.com/file/lbe6ghkv1bl8sv2/INKAS.lua/file

**Comment by Spartan8-8** [comment]
> Ur mapper (Hammer) used Ikzelfs broken converter. Which Hammer told me to sort it for ya.
> Here u go : https://www.mediafire.com/file/gg9klv24ztyy8sj/INKAS.lua/file

He has not mapped our ELK base

**Comment by L1nkan** [comment]
> > Ur mapper (Hammer) used Ikzelfs broken converter. Which Hammer told me to sort it for ya.
> > Here u go : https://www.mediafire.com/file/gg9klv24ztyy8sj/INKAS.lua/file
> 
> He has not mapped our ELK base

He sent me the map file though xD

**Comment by Ahren7413** [comment]
👍

**Comment by Spartan8-8** [comment]
😁😁
