### ISSUE TITLE
B~B Gate codes

### ISSUE THREAD

**Issue by iMatizZ** [saesrpg/saesrpg-gang#217]
Hello again ! :pp 
We have edited our gates/markers codes you can check in file. Tag me or dm me in discord if anything wrong :Dd 

Markers : http://www.mediafire.com/file/8ukkv3eklw8sfvt/markers.txt/file
Gates : http://www.mediafire.com/file/j04vukkqanmdp31/gates.txt/file

Thanks !

**Comment by Ahren7413** [comment]
👍
