### ISSUE TITLE
 ICE-Immigration & Customs Enforcement Skins change

### ISSUE THREAD

**Issue by ryadmahsoudi** [saesrpg/saesrpg-gang#219]
Hello 
We need to change skin of ice special unit to Swat skin and for ice agent too
https://www.mediafire.com/file/we6ynz33d50676h/ICE_Agent.txd/file
https://www.mediafire.com/file/j78lo1tm2ejjkar/ICE_special_unit.txd/file
Thanks

**Comment by Ahren7413** [comment]
The shaders exceed the maximum size limit. https://saesrpg.uk/topic/5633/shader-size-limits/6

**Comment by SScorpyo** [comment]
![alt text](https://imgur.com/dgux74q.png)
