### ISSUE TITLE
Medellin - Changes

### ISSUE THREAD

**Issue by WenDo21** [saesrpg/saesrpg-gang#223]
Hello, when we reached level 2 and the rewards were requested and added, Licano told us that our Togglewalk style isn't working, so we would like to add another one, and a small spawn code change.

Spawn code: https://pastebin.com/fKH5ELnH
Togglewalk : MOVE_GANG2 | 122

Sincerely,
Medellin HQ

**Comment by Ahren7413** [comment]
👍
