### ISSUE TITLE
S.W.A.T Spawns & Skins changes.

### ISSUE THREAD

**Issue by DenisIldis** [saesrpg/saesrpg-gang#225]
_______________________________________________________________________________________________________________
**Spawns:**

Spawns code: https://pastebin.com/27ffdcyh
______________________________________________________________________________________________________

**New Skin Shaders:**

**Note:** Those skins will be added to the current SWAT shaders, which means those skins will be added to both SWAT Officer & SWAT Tactical Paramedic spawns.

Skin name: bfyst
Skin ID: 13
File: https://www.mediafire.com/view/4n25wlgzgcd0izv/swat_female.dds/file

 ['S.W.A.T. Officer']={
    [13]={['fileName']='swat_female.dds',['textureName']='bfyst'},
},

['S.W.A.T. Tactical Paramedic']={
    [13]={['fileName']='swat_female.dds',['textureName']='bfyst'},
},
______________________________________________________________________________________________________

Skin name: lapd1
Skin ID: 280
File: https://www.mediafire.com/view/qvmibskw4i9kqbi/swat_officer.dds/file

 ['S.W.A.T. Officer']={
    [280]={['fileName']='swat_officer.dds',['textureName']='lapd1'},
},

['S.W.A.T. Tactical Paramedic']={
    [280]={['fileName']='swat_officer.dds',['textureName']='lapd1'},
},
____________________________________________________________________________________________________

Thanks in advance!

**Comment by Ahren7413** [comment]
👍
