### ISSUE TITLE
SAFP Changes

### ISSUE THREAD

**Issue by MrSlowGuy** [saesrpg/saesrpg-gang#226]
Hello, these are the new changes we would like to request for new SAFP Base and skins.

**Gates** = [link](https://cdn.discordapp.com/attachments/705696815193915452/714296229236047882/gates.txt)
(can you keep our current gates in interior since we are using same interior)

**Markers** = [link](https://cdn.discordapp.com/attachments/705696815193915452/714296657856036954/markers.txt)

**Spawns** = [link](https://cdn.discordapp.com/attachments/705696815193915452/714297296686284840/spawns.txt)

**Peds** = [link](https://cdn.discordapp.com/attachments/705696815193915452/714297556988854272/peds.lua)

**Map shaders** = [link](https://cdn.discordapp.com/attachments/680179058122031139/719000123111374858/map-shaders.rar)

**Base files and including everything** (exterior,interior,shaders,gates,markers,spawn locations, and peds) [here](https://cdn.discordapp.com/attachments/705696815193915452/714284782170931210/safp_files.rar)

--------

**Skin shaders**
`
[Link ](https://cdn.discordapp.com/attachments/705696815193915452/714286840710168617/SAFP_Hern.dds)
["SA Federal Police Officer"]={
    [267]={["fileName"]="SAFP_Hern.dds",["textureName"]="Hern"},
},
[link](https://cdn.discordapp.com/attachments/705696815193915452/714286595011903518/SAFP_SWAT.dds)
["SA Federal Police Officer"]={
    [285]={["fileName"]="SAFP_SWAT.dds",["textureName"]="swat"},
},

------
[link](https://cdn.discordapp.com/attachments/705696815193915452/714286592625475654/SAFP_Marshal_FBI.dds)
["SA Federal Police Marshal"]={
    [286]={["fileName"]="SAFP_Marshal_FBI.dds",["textureName"]="fbi"},
},
[link](https://cdn.discordapp.com/attachments/705696815193915452/714286590498832412/SAFP2.dds)
["SA Federal Police Marshal"]={
    [285]={["fileName"]="SAFP2.dds",["textureName"]="swat"},
},

`
-------

Atm location : (x=2081.80004 y=-2081 z=13.1999 rotation=180)

**Comment by Ahren7413** [comment]
👍
