### ISSUE TITLE
Underground Empire Updates.

### ISSUE THREAD

**Issue by UE-Arctic** [saesrpg/saesrpg-gang#227]
Hi, we'd like to update/add the following.
Gang safe: {2127.73, 1740.39, 20.39}
ATM: {2201.59,1597.9,68.4}

[Markers](https://pastebin.com/30V1F9U2).
[Base file](https://mega.nz/file/KBtDAZrS), encryption key will be sent in gm chat. I've just copy pasted the updated object table into the file Licano sent me to make it easier (hopefully).

Please update the regular spawn to the following:
```lua
<spawn id="Underground Empire" skin="240,172,186" x="2192.517" y="1600.65" z="68.74" rot="180" weapons="2,1;24,250;27,250;29,350;31,450;34,150;46,1;16,10;41,4000" 
description="Underground Empire is an organized crime syndicate." r="80" g="0" b="0" restricted="gang,UndergroundEmpire" ganglevelrestriction="0" />
```

Best regards UE.

**Comment by Ahren7413** [comment]
:+1:
