### ISSUE TITLE
Los INKAS Changes

### ISSUE THREAD

**Issue by Chafloque** [saesrpg/saesrpg-gang#228]
_Good day Gang Managers, I am here representing the INKAS HQ team to make some small but important changes to our Level 2 rewards._

_The first change is related to the arrangement of the weapons of our spawn, removing the dildo for more comfort._
`weapons="1,1;22,75;25,50;28,150;46,1;41,4000"`

The second change is from our second skin, we wanted to replace the Balla with a cap (104) to the skin of Jizzy (296)
`skin="293,296"`

Thanks for your attention
Chafloque

**Comment by Ahren7413** [comment]
👍
