### ISSUE TITLE
SAPA group has no police access

### ISSUE THREAD

**Issue by tut001** [saesrpg/saesrpg-gang#23]
Oi

SAPA group spawns has issues with gates, radio, among other police related features missing. It's also been mentioned to me that we can't enter our own vehicles.
As a last note, I've had issues with adding/removing people (including myself) via ingame HQ group panel. I can't add people as cadet nor instructor.

none of said issues existed prior to converting, so it's probably a setting that's not been moved yet

**edit**: Cadets has access to their own vehicles, though instructor and hq doesn't

**Comment by SAESKain** [comment]
Gates and radio will be live next patch. As for "other police related features" my mind reading skills aren't quite that developed just yet so you'll have to get back to me on that one.

PM Hesha/Nicus for vehicle fixes.

**Comment by tut001** [comment]
Solved, created a new request before seeing your response, sorry. thank you!
