### ISSUE TITLE
Navy Malistrip level 2 rewards

### ISSUE THREAD

**Issue by bazuka36** [saesrpg/saesrpg-gang#231]
Hello everyone, 

here by I would like to request the level 2 requests of Navy Malistrip.

**Spawn:**

`< spawn id="Navy Malistrip" skin="19,298" x="2011.98730" y="3007.54736" z="5.76313" rot="0" weapons="15,1;22,75;25,50;28,150;46,1;41,4000"
description="Somalian pirates who've decided to discover beyond the horizon, the new captains of San Andreas." r="92" g="125" b="108" restricted="gang,Navy_Malistrip" ganglevelrestriction="0" />`

**Skin shader:**
`["Navy Malistrip"]={[19]={["fileName"]=NavM.dds',["textureName"]="bmydj"},},`
File: https://ufile.io/56qmcmiy

**Base**
https://ufile.io/a0tmps7w

**Base Shaders**
Lua file, images, meta everything
https://ufile.io/guw52w4c

**Spray tag**
Line: 
`["Navy Malistrip"]="images/NavMspray.dds",`
File: https://ufile.io/uterdkh2

**Save disk**
We want to request a boat disk and a car disk.
Car disk: {2025.92981, 2911.27490, 46.35354}
Boat disk: {1946.33118, 3031.95996, 5.76563}

**Job**
/sell (arms)

**Vehicles**
_Remove:_
Jetmax, Picador, at LS pirate
_Add:_ 
Shamal
Squalo
Tropic
Infernus
picador

**Comment by Ahren7413** [comment]
:+1:
