### ISSUE TITLE
The Royals - Level 1 Rewards

### ISSUE THREAD

**Issue by richard42050** [saesrpg/saesrpg-gang#232]
We would like to request two police cruisers without the siren on top behind the LS Court, Royals Base and an official Teamspeak3 channel. The squad panel name is ''Royals'' 
The cruisers are to be painted with the 15171D colour code, here are the screen of the places for the cruisers to be placed:

![mta-screen_2020-06-05_02-44-23](https://user-images.githubusercontent.com/63075018/83820918-97e80980-a6d6-11ea-927a-a82355480131.png)

**Comment by DROTDROT** [comment]
Level and vehicles fees collected.
