### ISSUE TITLE
CripZ Skin Changes

### ISSUE THREAD

**Issue by AdemBygt** [saesrpg/saesrpg-gang#235]
Spawn Codes = https://pastebin.com/40ggaMg8

Skin DDS Files = http://fileload.info/8w27838gwcq9

Skin PNG Files=

ogloc [293] = https://i.imgur.com/7SgWku1.png 
ryder [271] = https://i.imgur.com/88urIIF.png
gangrl3 [195] = https://i.imgur.com/WD8EPRx.png
vla3 [116]  = https://i.imgur.com/yLnudqI.png

**Comment by Ahren7413** [comment]
https://saesrpg.uk/topic/5633/shader-size-limits

**Comment by AdemBygt** [comment]
Spawn Codes = https://pastebin.com/40ggaMg8

Skin DDS Files = http://fileload.info/c7x9y9fge43j


Skin PNG Files=

ogloc [293] = https://i.imgur.com/cIwDsS4.png
ryder [271] = https://i.imgur.com/zlLHUMG.png
gangrl3 [195] = https://i.imgur.com/c1LuDU5.png
vla3 [116]  = https://i.imgur.com/gYtl4J1.png

**Comment by NanoBob** [comment]
For future reference, your request was incorrect. The texture name for the skin 195 is not `gangrl3`.
