### ISSUE TITLE
Updated SAFP Skins

### ISSUE THREAD

**Issue by MrSlowGuy** [saesrpg/saesrpg-gang#236]
Please update the skins mentioned below with the new files. Thank you!

`
[Link](https://cdn.discordapp.com/attachments/680179058122031139/726214744549097573/safp-hern.dds)
["SA Federal Police Officer"]={
[267]={["fileName"]="safp-hern.dds",["textureName"]="Hern"},
},
[link](https://cdn.discordapp.com/attachments/680179058122031139/726214747514470450/safp-swat.dds)
["SA Federal Police Officer"]={
[285]={["fileName"]="safp-swat.dds",["textureName"]="swat"},
},

[link](https://cdn.discordapp.com/attachments/680179058122031139/726214741378203648/safp-FBI.dds)
["SA Federal Police Marshal"]={
[286]={["fileName"]="safp-FBI.dds",["textureName"]="fbi"},
},
 
`

**Comment by Ahren7413** [comment]
:+1:
