### ISSUE TITLE
S.W.A.T Changes/Updates

### ISSUE THREAD

**Issue by DenisIldis** [saesrpg/saesrpg-gang#238]
**Base Shaders PNG's**: 

Base map &  base shaders: https://pastebin.com/PpVNFGXx

swat_banner: https://imgur.com/a/3vbiD2S ( https://s4.aconvert.com/convert/p3r68-cdx67/aotp1-94dpw.dds )

 *Note: The billboard shade will be added to the current 2 shades that SWAT already has (The base shader code is updated with the third shaded).
______________________________________________________________________________________________________________

**NPC's & Gates:**

Peds/NPCs: https://pastebin.com/BMjppMyy (Updated).

Gates: https://pastebin.com/0395w0PL (Updated).

**Comment by Ahren7413** [comment]
👍
