### ISSUE TITLE
Generation X - Level 3 Rewards

### ISSUE THREAD

**Issue by Mrwann** [saesrpg/saesrpg-gang#240]
Gates / Markers / Spawn codes: https://pastebin.com/Pk5s3KpW
______________
Interior map: https://pastebin.com/ug22iiKt
___________________
Interior shader: https://uptobox.com/n7fg4n0vhukh

[ { "textures": [ "greyground256" ], "name": "x-int1", "fileName": "images/jailground.dds" } ]
__________________
---EXTERIOR---
https://uptobox.com/9egvyfpkj097

SHADER DOWNLOADS
[ { "textures": [ "taxi_256", "drvin_front", "ahoodfence2", "lasdockbar" ], "name": "x-wall", "fileName": "images/ink-ground.dds" } ]

[ { "textures": [ "sjmshopbk", "tislndshpillar01_128" ], "name": "x-wall2", "fileName": "images/cc-ground.dds" } ]

[ { "textures": [ "greyground256128", "drvin_back" ], "name": "x-ground", "fileName": "images/jailground.dds" } ]

____________________

Exterior map: https://pastebin.com/64djv1uk

Skin Shaders:
-------------
ID: 91
Name: Wfyri 
File: https://uptobox.com/951u9cg0e2n0

["Generation X"]={
[91]={["fileName"]='wfyri.dds',["textureName"]="wyfri"},
},

ID: 120
Name: triboss
File: https://uptobox.com/4ypfmr8vb66z

["Generation X"]={
[120]={["fileName"]='FILE-NAME.dds',["textureName"]="triboss"},
},

Togglewalk : MOVE_GANG2 | 122

**Comment by Ahren7413** [comment]
👍
