### ISSUE TITLE
Hell Soldiers - Level 2 rewards

### ISSUE THREAD

**Issue by candi1312** [saesrpg/saesrpg-gang#241]
```<spawn id="Hell Soldiers" skin="102,104" x="2151.42871" y="-1588.84387" z="16.74335" rot="159.004821" weapons="10,1;22,75;25,50;28,150;46,1;41,99999"```
```description="Hell Soldiers are the leading group of drug dealers in San Andreas. We bring hell to earth!" r="85" g="33" b="140" restricted="gang,Hell_Soldiers" ganglevelrestriction="0" />```

Base:
File: https://pastebin.com/UPeUu9yR

Base Shaders:
File: https://pastebin.com/H3by9hpb
Shader screens: 2 links incase something is wrong
https://mega.nz/folder/CmQhgYTR#Zz3PnTo6LCE-vuHrPgHO8Q
https://ufile.io/f/t8ny5

Spray tag:
Line: ["Hell Soldiers"]="images/HSspray.dds"
File: https://ufile.io/py91npj4

Save disk:
car disk: 2149.75049 -1594.41150 14.35156

Job:
/sell(drugs)

Vehicles:

position can be dealth while we interact in game

Some donations needs to be moved

-Keep our current cars (yosemite and pony)
-Maverick
-Huntley
-Tahoma

**Comment by Ahren7413** [comment]
👍 

Acceptance fee collected.
