### ISSUE TITLE
Medellin - Level 3 Rewards

### ISSUE THREAD

**Issue by WenDo21** [saesrpg/saesrpg-gang#243]
We would like to request our rewards for the level we gained the last month.

<< BASE >>
LUA: https://ufile.io/chaw2h9w
MAP: https://ufile.io/54thr01h
( .map file also added in-case the lua is not converted good )

<< SPAWN >>
https://pastebin.com/zD9zmpK4

<< MARKERS >>
https://pastebin.com/1TK5M8UQ

<< GATES >>
https://pastebin.com/yZsWiFYz

<< VEHICLES >>
- Remove all and set others.

**Comment by Ahren7413** [comment]
👍

**Comment by WenDo21** [comment]
@Ahren7413 Edited

**Comment by Ahren7413** [comment]
👍
