### ISSUE TITLE
Organization Zero's Changes

### ISSUE THREAD

**Issue by DravenCG** [saesrpg/saesrpg-gang#246]
Hello.

To begin with I'd like to request the removal of our current skin Omyri, ID:59 from Organization Zero spawn. We will move pimp skin from Organization Zero Nobility  to Organization Zero spawn and add somyri, ID:186 to Organization Zero Nobility spawn. Also we will change and add shaders for Andre, Pimp respectively.

Also we would like to make some changes in our weapons.
Spawn: https://pastebin.com/ti3xJ1DD
Shaders:

File: https://www.dropbox.com/s/ocwo8yb5a5fb7p6/Z1.dds?dl=0
Texture name: andre
Spawn name: Organization Zero
Model ID: 303

File: https://www.dropbox.com/s/01cmdrb4w12qt59/bmypimp.rar?dl=0
Texture name: bmypimp
Spawn name: Organization Zero
Model ID: 249

File: https://www.dropbox.com/s/wrx183p683rgo1o/sOMYRI.rar?dl=0
Texture name: somyri
Spawn name: Organization Zero Nobility
Model ID: 186

Note: Updated to match level 4 rewards.

**Comment by Ahren7413** [comment]
👍
