### ISSUE TITLE
The Royals - Level 2 Rewards

### ISSUE THREAD

**Issue by richard42050** [saesrpg/saesrpg-gang#247]
Hello, we would like to request the level 2 rewards of Royals as the following:

- **Spawn codes can be found in the link:** 

https://pastebin.com/MvpSY9Xn

- **Base mapping and shader files can be found in the rar file by this link:** 

https://cdn.discordapp.com/attachments/592716487417004042/738512485480661093/Royals.rar

- **Skin shader file can be found by this link:** 

https://cdn.discordapp.com/attachments/742335941787648060/743082331275001976/abxkt-vovzn.dds

**Skin ID:** 186

**Model Name:** somyri

**Marker codes can be found by this link:** 

https://pastebin.com/0P3mVfL6

Vehicles will be dealt in-game as the positions of the cars are to shown after the mapping. We would like to request the ability to use /coord and ''MOVE_BLINDMAN | 127'' on /togglewalk.

**Comment by Ahren7413** [comment]
👍
