### ISSUE TITLE
Navy Malistrip level 3 requests

### ISSUE THREAD

**Issue by bazuka36** [saesrpg/saesrpg-gang#248]
Hello, those are the changes we want as Navy Malistrip after we got level 3.

**Markers**
https://pastebin.com/mgEFxig5

<interior restriction="team,Official Gangs,Criminals,CLO,Admins" name="NavMCarrier">
    <entry pos="2018.8000488281,2930.3999023438,46.2" rotation="90" int="0" dim="0" />
    <exit pos="2174.1000976563,5315.7001953125,4998.90625" rotation="90" int="0" dim="352" />
</interior>

<interior restriction="team,Official Gangs,Criminals,CLO,Admins" name="NavMCarrier2">
    <entry pos="2174.19434,5327.84619,4998.90625" rotation="90" int="0" dim="352" />
    <exit pos="2019.79370, 3115.50757, 10.38125" rotation="90" int="0" dim="0" />
</interior>

<interior restriction="class,Navy Malistrip,Admin" name="NavMCarrier3">
    <entry pos="2028.03015, 2930.24561, 46.26563" rotation="90" int="0" dim="0" />
    <exit pos="2232.74609, 5268.22461, 4998.99951" rotation="90" int="0" dim="352" />
</interior>

<interior restriction="class,Navy Malistrip,Admin" name="NavMtower">
    <entry pos="1901.61108, 2995.95044, 50.64358" rotation="90" int="0" dim="0" />
    <exit pos="2021.82629, 2930.38599, 46.26563" rotation="90" int="0" dim="0" />
</interior>

<interior restriction="class,Navy Malistrip,Admin" name="NavMHelicopter">
    <entry pos="2042.06091, 3111.86401, 24.58058" rotation="90" int="0" dim="0" />
    <exit pos="2076.00464, 3110.74634, 13.80313" rotation="90" int="0" dim="0" />
</interior>

<interior restriction="class,Navy Malistrip,Admin" name="NavMroof">
    <entry pos="2024.96997, 2930.50513, 46.26563" rotation="90" int="0" dim="0" />
    <exit pos="2016.27173, 2906.21216, 54.14646" rotation="90" int="0" dim="0" />
</interior>

<interior restriction="class,Navy Malistrip,Admin" name="NavMtower2">
    <entry pos="2232.61255, 5265.11426, 4998.99951" rotation="90" int="0" dim="352" />
    <exit pos="2023.45105, 3038.23584, 89.25781" rotation="90" int="0" dim="0" />
</interior>

<interior restriction="class,Navy Malistrip,Admin" name="NavMtower3">
    <entry pos="2230.63672, 5265.09326, 4998.99951" rotation="90" int="0" dim="352" />
    <exit pos="1924.13550, 3019.12891, 33.13281" rotation="90" int="0" dim="0" />
</interior>

<interior restriction="class,Navy Malistrip,Admin" name="NavMcranetop">
    <entry pos="2228.63965, 5265.09033, 4998.99951" rotation="90" int="0" dim="352" />
    <exit pos="1979.85437, 3062.44751, 57.51511" rotation="90" int="0" dim="0" />
</interior>

<interior restriction="class,Navy Malistrip,Admin" name="NavMhulltop">
    <entry pos="2226.72998, 5265.08691, 4998.99951" rotation="90" int="0" dim="352" />
    <exit pos="2051.58545, 3115.41504, 48.32494" rotation="90" int="0" dim="0" />
</interior>

**New Spawn code**
`<spawn id="Navy Malistrip" skin="230,195" x="2001.58875" y="2925.12744" z="49.61719" rot="90" weapons="15,1;26,125;25,100;28,150;30,200;46,1;41,4000"
description="Somalian pirates who've decided to discover beyond the horizon, the new captains of San Andreas." r="92" g="125" b="108" restricted="gang,Navy_Malistrip" ganglevelrestriction="0" />
`

**Disks**
Boat disk `{1945.94360, 3088.91284, 2.76563}`
Car disk `{2031.82471, 2984.18335, 17.74896}`

**Shader lines**
`["Navy Malistrip"]={[195]={["fileName"]=navmviezehoer.dds',["textureName"]="gangrl3"},},`

**Gates**
https://pastebin.com/P0pbdiN2

**Vehcile marker (restricted to NavM please)**
`    -- colX, colY, colZ, colWidth, colLength, colHeight, warpX, warpY, warpZ, rotX
  {2005.2, 2857, 21.6,13,15,7, 1957.58838, 2989.47046, 18.6, 0}, -- Outside
  {1949, 2980, 16,18,4,5, 2016.97339, 2844.21338, 19.5, 210} -- Inside
 }`

**Skin shaders**
https://ufile.io/lfbrtq1e

**NavM level 3 base (shaders, luas everything)**
https://ufile.io/0h5deqyz

**Togglewalk**

MOVE_GANG1

**Comment by Ahren7413** [comment]
Rejected due to being level 2.

**Comment by bazuka36** [comment]
Bump & Update
