### ISSUE TITLE
UE Reward Changes

### ISSUE THREAD

**Issue by UE-Arctic** [saesrpg/saesrpg-gang#249]
Hello, we'd like to request the following changes to our organisation.

**Skin changes**
We'd like to replace skin ID 172 on the first spawn (Underground Empire) with the shadered skin ID 40
There's a little notice about the [ID 40 skin](https://cdn.discordapp.com/attachments/590301452014977044/741735208402812997/ID_40_-_HFYRI.zip), the skin uses two textures, one alpha cutout for jewelry and one bodymap for the character. The alpha cutout has been provided in .dds with dxt3 compression. The bodymap is standard .dds.

We'd also like to have the shadered 240 we already got on our first spawn (Underground Empire) added to our second spawn (Underground Empire Commission). The shader to this is already uploaded on the server. Heres the updated spawn [code](https://pastebin.com/1Aabzrma) for the hq spawn.

**Weapon setup**
Lastly we'd like max colt skills for the hq spawn (Underground Empire Commission)

**Comment by Ahren7413** [comment]
👍
