### ISSUE TITLE
Los INKAS - Level 3 Rewards

### ISSUE THREAD

**Issue by Chafloque** [saesrpg/saesrpg-gang#250]
_Greetings Gang Managers, below we will indicate the details of each of the rewards we would like to request._
### Weapons: 
_We will include and replace some devil tools to our current equipment as shown._

`weapons="1,1;24,125;26,100;28,200;30,200;46,1;41,4000"`

### Vehicles:
_As usual, we will include 3 public vehicles for the free use of our members._

- A **Dodo** _(the location will be shown ig)_
- A **Super GT** _(the location will be shown ig)_
- And finally a **Helicopter Maverick** _(the location will be shown ig)_

### Mapping:
_Small details of the exterior were deleted (the main door) because of the gate. The required .lua file is in this link._

**Exterior:**
https://www.mediafire.com/file/3vr60ugva5h83lr/file

**Gate:**

```
<!-- INKAS Gate -->
 
<trigger x="1011.9000244141" y="-68.5" z="26.89999961853" height="4.0" radius="4" movetime="2000" allowed="class,Los Inkas,Staff,Admin">
    <gate object="2924" pos=" 1011.9000244141,-68.5,26.89999961853,0,0,26.25" start=" 1011.9000244141,-68.5,26.89999961853,0,0,26.25" finish=" 1012,-68.5,26.89999961853,0,0,290" />
</trigger>
 
<!-- End of INKAS Gate -->
```

### Skin and Shader:
_We would like to change our current second skin (296) to the female (195) plus adding its respective shader._

**Shader:** https://www.mediafire.com/file/5oyy0ovcxmpqfpr/file

`skin="293,195"`

`["Los Inkas"]={[195]={["fileName"]=inkasfemaleskin',["textureName"]="gangrl3"},},`

_It remains to be clarified that each of our rewards must be tested (specially gate), if there is any problem that must be solved quickly, do not hesitate to contact me on Discord._

_Thanks in advance_
**Chafloque**

**Comment by Ahren7413** [comment]
👍
