### ISSUE TITLE
NavM -- Spawn code updates

### ISSUE THREAD

**Issue by Lincolnn22** [saesrpg/saesrpg-gang#252]
**Spawn:**

` < spawn id="Navy Malistrip" skin="69,104" x="2011.98730" y="3007.54736" z="5.76313" rot="0" weapons="15,1;22,75;25,50;28,150;46,1;41,4000" description="Somalian pirates who've decided to discover beyond the horizon, the new captains of San Andreas." r="92" g="125" b="108" restricted="gang,Navy_Malistrip" ganglevelrestriction="0" /> `

___

**Shader**

*Line*: ` ["Navy Malistrip"]={[104]={["fileName"]=NavM1.dds',["textureName"]="ballas3"},}, `

*File*: https://easyupload.io/8injoh

**Comment by Ahren7413** [comment]
👍
