### ISSUE TITLE
NwA - Level 1 rewards

### ISSUE THREAD

**Issue by laggiaze** [saesrpg/saesrpg-gang#253]
Hi there
I would like to request our vehicles and a teamspeak3 chanel

**Vehicles**:
 We would like to get sultan and huntley in our base

Color: 1E0B21
Gang panel name: ‎Niggaz-wit-Attitudes

**Location:**
 
![base2](https://user-images.githubusercontent.com/49839598/91915962-9376c100-ecc4-11ea-900c-5b13e203360e.png)

**Comment by Ahren7413** [comment]
The fee was paid and rewards given in-game.
