### ISSUE TITLE
Sons of Anarchy lvl 3 rewards

### ISSUE THREAD

**Issue by NanoBob** [saesrpg/saesrpg-gang#256]
All Sons of Anarchy rewards have been added to the git repository on a seperate branch.
In order to pull them into master run `git pull origin feature/soa-lvl-3`.

The rewards contain:
- Second skin shader (skin 299, claude)
- Interior
- 1 warp marker (to interior)
- 3 gates (all in interior)
- More weapons on spawn

These rewards have all been tested on a local server and should be functional.

**Comment by Ahren7413** [comment]
👍
