### ISSUE TITLE
Organization Zero's updates 

### ISSUE THREAD

**Issue by Sira188** [saesrpg/saesrpg-gang#259]
Hello there, we would like to finally update our exterior and interior.

Spawn code : https://pastebin.com/juVqfkvM

and everything related to exterior/interior ( mapping, markers , doors and shaders ) can be found here : http://www.mediafire.com/file/sr8ynmj3zavnfjc/ZBASE.rar/file

Vehicles will be sorted ingame 

And photo which shows the disk's location (the heart) and the vehicle spawning location ( the placed vehicle)
https://imgur.com/a/6VnIge9

**Comment by Ahren7413** [comment]
:+1:
