### ISSUE TITLE
The Company Skin Changes

### ISSUE THREAD

**Issue by SScorpyo** [saesrpg/saesrpg-gang#26]
Hello, i would like to request new skin:

**Spawn code change**: 
Skin with the ID 185 should be replaced with 186 and 93 with 85 on both *The Company* and *The Company High Council* spawns.

**Skin shaders code:**
```lua
	["The Company"]={
		[186]={['fileName']='THC4.dds',['textureName']='somyri'},
		[85]={['fileName']='THC.dds',['textureName']='vwfypro'},
	},
	["The Company High Council"]={
		[186]={['fileName']='THC4.dds',['textureName']='somyri'},
	},
```

**Skin download links:**
[Here](https://mega.nz/#!EUVAFQJC!N0dIz6dsL5n5u6jwwXrKIgcUNffaw4jZFFi7NI7SwOA).

Thank you for your time

**Comment by nicusi** [comment]
THC.dds shader does not fit skin ID 85. Please provide an updated THC.dds for that skin.

**Comment by MrMedEra** [comment]
@nicusi lemme check sec

**Comment by MrMedEra** [comment]
`THC.dds` for skin ID `85` : https://www.mediafire.com/file/dkei35ecavl5e2x/THC.dds

**Comment by nicusi** [comment]
Request sorted.
