### ISSUE TITLE
Black~Bullets Gate and Spawn Changes

### ISSUE THREAD

**Issue by Ahmed-khayry** [saesrpg/saesrpg-gang#260]
Hello!
we need our base interior gate C marker to be accessed by criminals only, since cops still can enter to marker, especially when we are regrouping for br's, they rush base and running to marker to arrest helpers/afks inside..
Photo of the marker: https://i.ibb.co/1zjKfz6/mta-screen-2020-10-03-20-58-48.png the marker at left side

```
<interior restriction="team,Criminals,Official Gangs,CLO" name="Black~Bullets Interior">
    <entry pos="-2519.513671875,-624.68981933594,132.78828430176
" rotation="90" int="0" dim="0" />
    <exit pos="2380.0866699219,2858.8879394531,73.268753051758
" rotation="270" int="0" dim="352" />
</interior>
```

 
We also want to fix our class "Black~Bullets Veteran" spawn to be accessed by Level 6 members and above.

```
<spawn id="Black~Bullets Veteran" skin="126" x="-2492.9543457031" y="-651.02960205078" z="148.26014709473" rot="90" weapons="28,350;27,250;24,250;46,1;10,1;41,4000;16,10;34,150;31,450" 
description="Black~Bullets Veteran - This spawn is used by the loyal members of B~B." r="255" g="69" b="0" restricted="Black~Bullets" ganglevelrestriction="6" />

```

Thank you.

**Comment by Ahren7413** [comment]
Due to the request being only about editing restrictions (which is easily doable) it was done, however in the future make sure to request the changes properly.
:+1:

**Comment by Ahmed-khayry** [comment]
<spawn id="Black~Bullets Veteran" skin="126" x="-2492.9543457031" y="-651.02960205078" z="148.26014709473" rot="90" weapons="28,350;27,250;24,250;46,1;10,1;41,4000;16,10;34,150;31,450" 
description="Black~Bullets Veteran - This spawn is used by the loyal members of B~B." r="255" g="69" b="0" restricted="Black~Bullets" ganglevelrestriction="6" />

**Comment by Ahmed-khayry** [comment]
Nothing is done yet, restrictions still opened to cops also the veteran spawn still the same. anyways I fixed the changes but still need to make sure of the interior dimension number

**Comment by Ahmed-khayry** [comment]
> 
> 
> Due to the request being only about editing restrictions (which is easily doable) it was done, however in the future make sure to request the changes properly.
> 👍

restrictions still opened to cops also the veteran spawn still the same. anyways I fixed the changes but still need to make sure of the interior dimension

**Comment by Ahren7413** [comment]
Yeah, it is because the updates gotta be pushed in game, as soon as they're, you'll notice the change
