### ISSUE TITLE
Los Lunas - Level 1 rewards

### ISSUE THREAD

**Issue by Line558** [saesrpg/saesrpg-gang#261]
Hi there
I would like to request our vehicles
Vehicles:
We would like to get sultan and picador in our base

Color: 855521
Gang panel name: ‎Los_Lunas

Location:![base](https://images-ext-1.discordapp.net/external/7swq7d04y_NcOaKLYHiGSqzDY0l88qGfvehh-FlBBu0/https/i.imgur.com/NYzJEWP.png)

**Comment by Ahren7413** [comment]
Fee paid, cars placed.
