### ISSUE TITLE
NavM -- New spawn code

### ISSUE THREAD

**Issue by Lincolnn22** [saesrpg/saesrpg-gang#262]
Spawn:

< spawn id="Navy Malistrip" skin="69,230" x="2011.98730" y="3007.54736" z="5.76313" rot="0" weapons="15,1;22,75;26,50;28,150;46,1;41,4000" description="Somalian pirates who've decided to discover beyond the horizon, the new captains of San Andreas." r="92" g="125" b="108" restricted="gang,Navy_Malistrip" ganglevelrestriction="0" />

___

 *Line* :    ["Navy Malistrip"]={[230]={["fileName"]=navmmogool.dds',["textureName"]="swmotr5"},},

*FIle* : https://ufile.io/0a8uocih

**Comment by Ahren7413** [comment]
:+1:
