### ISSUE TITLE
Los INKAS Level 4 Rewards 

### ISSUE THREAD

**Issue by Chafloque** [saesrpg/saesrpg-gang#263]
**_Greetings Gang Managers, below we will indicate the details of each of the rewards we would like to request. We re sorry for the delay but we had some problems and theyre solved now._** 

### Mayor Changes in our current spawn and a new one.

**Los Inkas Spawn Changes: Different Skins and Weapons Update**

`<spawn id="Los Inkas" skin="293,193,126" x="1020" y="-57.900001525879" z="26.39999961853" rot="188.997940" weapons="1,1;24,175;27,200;31,350;34,100;46,1;41,4000" description="INKAS, more than a word is a way of acting, a tribute to the empire that once reigned over Latin America, in addition to the terrorist group that dominated Peru during the 90s." r="74" g="9" b="43" restricted="gang,Los_INKAS" ganglevelrestriction="0" />`

**New Spawn:** “Los Inkas Capos”

`<spawn id="Los Inkas Capos" skin="44" x="886.20001220703" y="-34.700000762939" z="63.200000762939" rot="0.00274658" weapons="1,1;24,175;27,200;31,350;34,100;46,1;41,4000" description="The most respected members in Los INKAS." r="45" g="6" b="26" restricted="gang,Los_INKAS" ganglevelrestriction="5" />`

### Shaders in Los Inkas spawns:

**Shader 1:** _The same we already have in 293_

**Shader 2:** _Replace the second shader in the girl with a new one for the skin 126._
http://www.mediafire.com/file/1a1de42k5srpmfh/SkinJoven.dds/file
`["Los Inkas"]={[126]={["fileName"]=SkinJoven.dds',["textureName"]="vmaff3"},},`

**Shader 3:** http://www.mediafire.com/file/oxu1w5anuld36s0/ViejoJoto.dds/file
`["Los Inkas Capos"]={[44]={["fileName"]=ViejoJoto.dds',["textureName"]="hmost"},},
`

### New Interior and Mayor Exterior Changes.(POSTED)

Exterior .lua and .map: http://www.mediafire.com/file/geelg2wrr9ryzw0/INKAS8.zip/file

Interior .lua and .map: http://www.mediafire.com/file/rl4vape8we09czp/INKAS_Interior.zip/file

**Map Shader:**

`[ { "textures": [ "vgEastbillbrd02" ], "name": "Inkas-Logo", "fileName": "INKAS-Shaders/Inkas-Logo.dds" } ]`
https://app.mediafire.com/hmehni1fuy6ua

`[ { "textures": [ "vgslockup" ], "name": "villainnwall02_128", "fileName": "Paredes.dds" } ]`
http://www.mediafire.com/file/tqnfs0aq4liz71l/Paredes.dds/file

`[ { "textures": [ "vgslockup" ], "name": "carpark_128", "fileName": "Piso1.dds" } ]`
http://www.mediafire.com/file/ja3g1sypgtgvmtk/Piso1.dds/file

**Gates:**

```
<!-- INKAS Gates -->

<trigger x="1120.5999755859" y="-55.400001525879" z="19.89999961853" height="10" radius="9" movetime="1550" allowed="class,Los Inkas,Los Inkas Capos" interior="0" dimension="0"> <gate object="980" pos=" 1121.2998046875,-57.700099945068,21.700000762939,0,0,254.49279785156" start=" 1121.2998046875,-57.700099945068,21.700000762939,0,0,254.49279785156" finish=" 1121.2998046875,-57.700099945068,27.700000762939,0,0,254.49279785156" />


<trigger x="932.29998779297" y="-90.699996948242" z="17.700000762939" height="10" radius="10" movetime="1550" allowed="class,Los Inkas,Los Inkas Capos" interior="0" dimension="0"> <gate object="980" pos=" 930.7998046875,-92.5,19.39999961853,0,0,90.499877929688" start=" 930.7998046875,-92.5,19.39999961853,0,0,90.499877929688" finish=" 930.7998046875,-92.5,25.39999961853,0,0,90.499877929688" />

<trigger x="1087.9000244141" y="-54.599998474121" z="26.39999961853" height="5" radius="10" movetime="1200" allowed="class,Los Inkas,Los Inkas Capos" interior="0" dimension="0"> <gate object="969" pos=" 1086.900390625,-49.099609375,25.5,0,0,278.24523925781" start=" 1086.900390625,-49.099609375,25.5,0,0,278.24523925781"
finish=" 1086.900390625,-43.7,25.5,0,0,278.24523925781"/>

<trigger x="1041.1999511719" y="-53.400001525879" z="26.39999961853" height="5" radius="10" movetime="1200" allowed="class,Los Inkas,Los Inkas Capos" interior="0" dimension="0"> <gate object="2930" pos=" 1041.5,-54.2998046875,28,0,0,189.99755859375" start=" 1041.5,-54.2998046875,28,0,0,189.99755859375"
finish="1041.5,-52,28,0,0,189.99755859375""/>

<trigger x="880.70001220703" y="-32.900001525879" z="63.599998474121" height="5" radius="10" movetime="1200" allowed="class,Los Inkas Capos" interior="0" dimension="0"> <gate object="2930" pos=" 881.09997558594,-32.200000762939,65.199996948242,0,0,337" start="881.09997558594,-32.200000762939,65.199996948242,0,0,337" 
finish="881.09997558594,-30.5,65.199996948242,0,0,337" />

<!-- End of INKAS Gates →

```

**Teleports:**

```
<-- INKAS INTERIORS -->


<interior restriction="class,Los Inkas Capos" name="BaseDoor to a Room">
<entry pos="1060.6999511719,-51.900001525879,26.39999961853" rotation="180" int="0" dim="0" />
<exit pos="1029,7,39.900001525879" rotation="203125" int="0" dim="9" />
</interior>

<interior restriction="team,Official Gangs,Criminal" name="TrainDoor to Station">
<entry pos="958,-77.3,21" rotation="180" int="0" dim="0" />
<exit pos="1050.3000488281,-42.5,24.60000038147" rotation="0.00274658" int="0" dim="9" />
</interior>

<interior restriction="class,Los Inkas,Los Inkas Capos" name="BackDoor - Entrance">
<entry pos="1021.0999755859,-84.099998474121,3.0999999046326" rotation="9233434" int="0" dim="0" />
<exit pos="1067.1999511719,-62.700000762939,21.10000038147" rotation="180" int="0" dim="0" />
</interior>

<interior restriction="class,Los Inkas,Los Inkas Capos" name="Station to a Room">
<entry pos="1060.0999755859,5.4000000953674,25.700000762939" rotation="1000" int="0" dim="9" />
<exit pos="1076.1999511719,6.9000000953674,33.5" rotation="9203125" int="0" dim="9	" />
</interior>

<interior restriction="class,Los Inkas Capos" name="Cata to Skull">
<entry pos="870.5,-24.799999237061,64" rotation="190" int="0" dim="0" />
<exit pos="1004.200012207,-62.799999237061,27" rotation="352.394592" int="0" dim="0" />
</interior>

<interior restriction="class,Los Inkas,Los Inkas Capos" name="Base to Roof">
<entry pos="1057.0999755859,-52.099998474121,26.39999961853" rotation="3203125" int="0" dim="0" />
<exit pos="1063.1999511719,-52.099998474121,84.599998474121" rotation="0.00274658" int="0" dim="0" />
</interior>

<-- END OF INKAS INTERIORS -->
```

**Vehicles**:
_As usual, we will include x public vehicles for the free use of our members.
They will be revealed the same time we deliver the Level Up money._

**Comment by DROTDROT** [comment]
X

**Comment by erentekingunduz** [comment]
**Fixed gates** : https://pastebin.com/YwhJAbag
