### ISSUE TITLE
Generation X Fixes

### ISSUE THREAD

**Issue by Mrwann** [saesrpg/saesrpg-gang#264]
**Generation X FIXES**

Base(Exterior,Interior and NPCs)
https://gofile.io/d/sySQlw

Spawn/Markers/Gates codes:
https://pastebin.com/BaXPGCbn

Base Shaders: (.dds files)
https://gofile.io/d/22WEFv

**Exterior Shaders codes**: https://pastebin.com/KeWmDrMd
**Interior Shaders codes**: https://pastebin.com/njEqywGB

Skin Shaders: (.dds files)
https://gofile.io/d/r9RG7g

Skin Shaders codes:
["Generation X"]={
[120]={["fileName"]='X1.dds',["textureName"]="triboss"},
},

["Generation X"]={
[240]={["fileName"]='X2.dds',["textureName"]="swmyri"},
},

["Generation X Respected"]={
[296]={["fileName"]='X3.dds',["textureName"]="jizzy"},
}, 

Spraypaint: https://gofile.io/d/XokWj1

["Generation X"]="images/Xspray.dds"
["Generation X Respected"]="images/Xspray.dds"

Togglewalk : MOVE_GANG2
We would like to have Drug Selling Ability and togglewalk for both Spawns also an icon for our base and the announcement when someone joins the gang, Thanks in advance.

**Comment by DROTDROT** [comment]
X
