### ISSUE TITLE
Organization Zero's Level 5 Rewards

### ISSUE THREAD

**Issue by DravenCG** [saesrpg/saesrpg-gang#266]
Hello !
I would like to request our level 5 rewards.

Spawn Code: https://pastebin.com/ZTvwSMQV

Secondary Job: Drug sell

ATM coordinates & Secreenshot: -1101.4776611328,-1633.5728759766,91.125503540039 /// https://i.imgur.com/wfmg2fi.png

Thank you in advance.

**Comment by DROTDROT** [comment]
X
