### ISSUE TITLE
NavM Level 3 rewards

### ISSUE THREAD

**Issue by Lincolnn22** [saesrpg/saesrpg-gang#268]
Hello, those are the changes we want as Navy Malistrip after we got level 3.

Markers
https://pastebin.com/mgEFxig5

New Spawn code
` <spawn id="Navy Malistrip" skin="230,195" x="2001.58875" y="2925.12744" z="49.61719" rot="90" weapons="15,1;26,125;25,100;28,150;30,200;46,1;41,4000" description="Somalian pirates who've decided to discover beyond the horizon, the new captains of San Andreas." r="92" g="125" b="108" restricted="gang,Navy_Malistrip" ganglevelrestriction="0" />` 

Disks
`Boat disk {1945.94360, 3088.91284, 2.76563} `
` Car disk {2031.82471, 2984.18335, 17.74896}`

Shader lines
` ["Navy Malistrip"]={[195]={["fileName"]=navmviezehoer.dds',["textureName"]="gangrl3"},},`

Gates
https://pastebin.com/P0pbdiN2

Vehcile marker (restricted to NavM please)
` -- colX, colY, colZ, colWidth, colLength, colHeight, warpX, warpY, warpZ, rotX {2005.2, 2857, 21.6,13,15,7, 1957.58838, 2989.47046, 18.6, 0}, -- Outside {1949, 2980, 16,18,4,5, 2016.97339, 2844.21338, 19.5, 210} -- Inside }`

Skin shaders
https://ufile.io/lfbrtq1e

NavM level 3 base (shaders, luas everything)
https://ufile.io/0h5deqyz

Togglewalk

MOVE_GANG1

**Comment by bazuka36** [comment]
Gates fixed 
https://pastebin.com/qv86P744
