### ISSUE TITLE
Speed trap

### ISSUE THREAD

**Issue by SAESSam** [saesrpg/saesrpg-gang#27]
As it stands, since SAPA turned into a group they are no longer in the speed trap excemption list as the other emergency teams are, 

Please fix,

**Comment by tut001** [comment]
i'd like to note that instructor spawn should have access to invite cadets
edit. just been made aware that our spawns can't open jail, pd and bank gates

**Comment by SAESSam** [comment]
> i'd like to note that instructor spawn should have access to invite cadets

Pls make seperate issue rather than hijacking this one tutty
