### ISSUE TITLE
Generation X - Skin change

### ISSUE THREAD

**Issue by Mrwann** [saesrpg/saesrpg-gang#281]
We would like to replace skin number 59 in Generation X Spawn with skin number 240

skin shader: https://www.mediafire.com/file/hkpbp8iks747g7p/swmyri.dds/file

["GenerationX"]={[240]={["fileName"]=swmyri.dds',["textureName"]="swmyri"},},

Thanks!

**Comment by SAESHenry** [comment]
Will be live next server update.
