### ISSUE TITLE
Generation X Spawn code update

### ISSUE THREAD

**Issue by Mrwann** [saesrpg/saesrpg-gang#284]
< spawn id="Generation X Council" skin="186" x="1180.75" y="-1155" z="131" rot="270" weapons="2,1;24,175;27,200;28,300;31,350;34,100;46,1;41,10000" 
description="This spawn Is for the very respected people In Generation X, They are the experts and the professionals, They are the high ranked people who should be very respected In the gang" r="93" g="81" b="99" restricted="gang,GenerationX" ganglevelrestriction="8" />

**Comment by SAESHenry** [comment]
Change will be applied on next update
