### ISSUE TITLE
HRMC - Level 1 Rewards

### ISSUE THREAD

**Issue by Franklin880** [saesrpg/saesrpg-gang#285]
2 gang vehicles - 2 Freeways next to our other freeways in our base in RC Dillimore colored (Primary: 000000, Secondary: 33033f), for everyone in hellraisers_mc /gang

The base:
https://i.imgur.com/hlP3Ps4.png

Position of the 1st freeway
https://i.imgur.com/aeRTi5Y.png

Position of the 2nd freeway
https://i.imgur.com/1pKCdJ6.png

___

A private role in SAES Gang Management named "Hell Raisers MC" colored #33033f

Gang HQs:
Franklin (Wask#2072)
Woytex (Woytex#0052)
Tomaz96 (Tomaz96#2729)
MrThomas (MrThomasツ#1853)
Thamond (Thamond#9353)
Zoom-In (Zoom-In#3613)

___

Private Forum & Private Role requested here:
https://github.com/saesrpg/saesrpg-web/issues/297

**Comment by SAESHenry** [comment]
Sorted
