### ISSUE TITLE
CripZ skin changes 2021

### ISSUE THREAD

**Issue by ZazaBast** [saesrpg/saesrpg-gang#287]
<spawn id="CripZ OG" skin="102,269" x="397" y="-2125.8994140625" z="15.60000038147" rot="0" weapons="10,1;41,9999;22,250;27,250;31,450;28,350;46,1;34,150;16,10" description="Designated spawn for the official gang CripZ! Located in Los Santos If you aint BLUE you aint TRUE! CripZ are an organised crime gang that are a product of their environment. They do anything to get by, carjacking, murder, slinging dope and much more" r="0" g="80" b="87" restricted="gang,CripZ~" ganglevelrestriction="5" />
 
 
<spawn id="CripZ" skin="114,293" x="361.79998779297" y="-2120.8999023438" z="15.60000038147" rot="0" weapons="10,1;41,9999;24,250;27,250;31,450;28,350;46,1;34,150;16,10" description="Designated spawn for the official gang CripZ! Located in Los Santos If you aint BLUE you aint TRUE! CripZ are an organised crime gang that are a product of their environment. They do anything to get by, carjacking, murder, slinging dope and much more" r="0" g="85" b="85" restricted="gang,CripZ~" ganglevelrestriction="0" />

DDS files of skin shaders for 3 skin .We want to keep VLA2 skin as original
https://cdn.discordapp.com/attachments/263283488491438081/806586025445949460/ballas1.dds 
https://cdn.discordapp.com/attachments/263283488491438081/806586029301301308/ogloc.dds
https://cdn.discordapp.com/attachments/263283488491438081/806586031704637500/smoke.dds

imgur links for skin shaders
ogloc [293] : https://i.imgur.com/cIwDsS4.png
ballas1[102] :  https://i.imgur.com/x7Ml5OU.png
smoke [269] : https://i.imgur.com/kwrUaAf.png

**Comment by ZazaBast** [comment]
<spawn id="CripZ OG" skin="102,269" x="397" y="-2125.8994140625" z="15.60000038147" rot="0" weapons="10,1;41,9999;22,250;27,250;31,450;28,350;46,1;34,150;16,10" description="Designated spawn for the official gang CripZ! Located in Los Santos If you aint BLUE you aint TRUE! CripZ are an organised crime gang that are a product of their environment. They do anything to get by, carjacking, murder, slinging dope and much more" r="0" g="80" b="87" restricted="gang,CripZ~" ganglevelrestriction="5" />
 
 
<spawn id="CripZ" skin="114,293" x="361.79998779297" y="-2120.8999023438" z="15.60000038147" rot="0" weapons="10,1;41,9999;24,250;27,250;31,450;28,350;46,1;34,150;16,10" description="Designated spawn for the official gang CripZ! Located in Los Santos If you aint BLUE you aint TRUE! CripZ are an organised crime gang that are a product of their environment. They do anything to get by, carjacking, murder, slinging dope and much more" r="0" g="85" b="85" restricted="gang,CripZ~" ganglevelrestriction="0" />

**Comment by ZazaBast** [comment]
https://pastebin.com/RaKxx2Vi

**Comment by SAESHenry** [comment]
Will be live next server udpate
