### ISSUE TITLE
MIT - Updates

### ISSUE THREAD

**Issue by SOLLOZZO-SAES** [saesrpg/saesrpg-gang#289]
Hello, there is the updates requested by GMs : 

---

~~**Fixed map (Exterior) [.zip file] :**~~ ✅ Live

---

~~**Fixed skin [.dds file] :**~~ ❌ Rejected

Model ID : 124
Model name : vmaff1

---

Warning : the storage provider will erase the files in 1 week

**Comment by SOLLOZZO-SAES** [comment]
~~**Fixed map (Exterior) [.zip file] :**~~ ✅ Live

Warning : the storage provider will erase the files in 1 week.

**Comment by SAESHenry** [comment]
This is now sorted
