### ISSUE TITLE
NNB level 5 Reward Update

### ISSUE THREAD

**Issue by louissaes** [saesrpg/saesrpg-gang#29]
Dear GM Team,

We're missing out on the new equipment (just nightvision goggles) and according to the level 5 rewards we can request more ammo. We'd also like to adjust our walkingstyle.

- For the "Third Echelon" spawn: 
weapons="3,1;23,250;27,250;29,450;31,450;34,150;17,10;41,2500;44,1;46,1;" 

Walkingstyle: MOVE_SNEAK    69

Thank you in advance, 

on behalf of NNB HQ.
-Louis

**Comment by louissaes** [comment]
Got the right walkingstyle number added

**Comment by ghost** [comment]
@louissaes  Walking style 69 is not available anymore due to easy abuse. Please request another one
