### ISSUE TITLE
NavM Captain skin change

### ISSUE THREAD

**Issue by bazuka36** [saesrpg/saesrpg-gang#291]
spawn code
`<spawn id="Navy Malistrip Captain" skin="104" x="2001.58875" y="2925.12744" z="49.61719" rot="90" weapons="15,1;27,200;28,300;31,350;34,100;46,1;41,4000" description="Captains of the Navy Malistrip." r="92" g="125" b="108" restricted="gang,Navy_Malistrip" ganglevelrestriction="5"/>
`

link
https://ufile.io/ul24vwt5
skin line
`["Navy Malistrip"]={[104]={["fileName"]=navmhenryisaniceperson.dds',["textureName"]="ballas3"},},`

**Comment by SAESHenry** [comment]
Will be live on next server update
