### ISSUE TITLE
UE skin change

### ISSUE THREAD

**Issue by UE-Arctic** [saesrpg/saesrpg-gang#292]
Hello, we'd like to request the following changes to our organisation.

**Skin changes**
Replace on class 'Underground Empire': 308 with 120 and apply this [shader](https://mega.nz/file/eAMTEA4Q#0irOT-TfsTlfk7fKz6gXyRqYQhmhMZ7XLa2bFhE9MVU)

Best regards UE.

**Comment by SAESHenry** [comment]
Will be live on next server update
