### ISSUE TITLE
NwA - level 3 rewards

### ISSUE THREAD

**Issue by laggiaze** [saesrpg/saesrpg-gang#294]
Hey I would like to request our level 3 rewards

If there is something wrong, contact me via discord: [Laggiaze#7947]

Spawn Codes:
```
<spawn id="Niggaz wit Attitudes" skin="300,270" x="2740.42310" y="-1944.10876" z="13.54688" rot="90" weapons="1,1;24,125;26,100;32,200;30,200;46,1;41,99999"
description="Niggaz wit Attitudes are the pioneers of the G-Funk in San Andreas.They are still on the top of rap business and now aiming to takeover the drug business in Los Santos" r="30" g="11" b="33" restricted="gang,Niggaz-wit-Attitudes" ganglevelrestriction="0" />

```
-

Skin shader:
["Niggaz wit Attitudes"]={[270]={["fileName"]=sweet.dds',["textureName"]="sweet"},},
file: https://drive.google.com/file/d/1PiXL3KzpeH17uFyRmMKh8z-IOYaTM6Pp/view?usp=sharing

-

MAPPINGS:
Exterior: https://pastebin.com/ZWYRK4yY
Interior: https://pastebin.com/ZDCM5gbW

-

SHADERS:
Shaders (lua): https://pastebin.com/FDVCtUXG
Shaders file: https://drive.google.com/drive/folders/1Mm7n5FLTOkL_tJSNXj3BjEnOSxxdx6TF?usp=sharing

-

Gates: https://pastebin.com/Br2cmBU2
Warp markers: https://pastebin.com/6TsaJ6ib

-

Vehicles:
We would like to get 3 more gang vehicles.

**Comment by laggiaze** [comment]
Shaders fixed

skin shader: https://drive.google.com/file/d/1PiXL3KzpeH17uFyRmMKh8z-IOYaTM6Pp/view?usp=sharing

Base Shaders: https://drive.google.com/drive/folders/1Mm7n5FLTOkL_tJSNXj3BjEnOSxxdx6TF?usp=sharing

**Comment by SAESHenry** [comment]
Will be live on next server update
