### ISSUE TITLE
Lunas - Level 3 Rewards

### ISSUE THREAD

**Issue by Line558** [saesrpg/saesrpg-gang#296]
Hey I would like to request our level 3 rewards

If there is something wrong, contact me via discord:[Matto#7711]

Spawn Code:https://www.mediafire.com/file/dkbsiw4ik6gpbev/SPAWNCODE.txt/file
- 

### Skin shader:

["Los Lunas"]={[240]={["fileName"]=lunasoff.dds',["textureName"]="swmyri"},},
file: https://mega.nz/file/m9JTyI6C#SohcDcxlQDKQt0LHrbit_uPRWIccryiA9GMlolyE8s0

- 

### MAPPINGS:

Exterior: https://www.mediafire.com/file/uc08mcnirgfu6az/exterior.lua/file
Interior: https://www.mediafire.com/file/4hhc8zear50dd82/interior.lua/file

- 

### SHADERS:
Shaders (lua): https://www.mediafire.com/file/vq379jm6vega5dn/LUNASEXTERIORSHADERS.txt/file
Shaders file: https://www.mediafire.com/file/b5w666z1jn5hqm7/LUNASINTERIORSHADERS.txt/file

- 

Gates: 
Warp markers: https://www.mediafire.com/file/u0od4rhja6o0rt3/GATESCODE.txt/file

Interiors:
Warp markers: https://www.mediafire.com/file/2vteleybhoqvmg7/MARKERSCODE_%25281%2529.txt/file

- 

Vehicles:
We would like to get 3 more gang vehicles.

**Comment by SpeeD1Pro** [comment]
**SPAWN CODE**
```
<spawn id="Los Lunas" skin="240,169" x="-372.70001220703" y="-1061.0999755859" z="60.00000762939" rot="0.00274658" weapons="10,1;24,125;26,100;28,200;30,200;41,99999;46,1"
description="Los Lunas A mafia thats focused killing and dealing drugs, focused on selling own products." r="133" g="85" b="33" restricted="gang,Los_Lunas" ganglevelrestriction="0" />
```

**Comment by SAESHenry** [comment]
Will be live on next server update
