### ISSUE TITLE
NwA lvl 3 fixes

### ISSUE THREAD

**Issue by laggiaze** [saesrpg/saesrpg-gang#297]
We would like to fix these 3 things

Markers:
https://pastebin.com/6TsaJ6ib

Shader:(we want change the file of graf.dds file
here is the file
https://drive.google.com/file/d/11vVmsOe-0D0GYubfIkUJskfhuwkk2z1R/view?usp=drivesdk

and our (invite advert) doesnt work
We would like to get it as well

Thank you

**Comment by SAESHenry** [comment]
Will be live on next server update
