### ISSUE TITLE
The Company Markers

### ISSUE THREAD

**Issue by Griffin687** [saesrpg/saesrpg-gang#298]
we would like to adjust one marker which is the ThCGetAway one. Please see below:

```
    <interior restriction="team,CLO,Official Gangs" name="ThCGetAway" >
        <entry pos="-1365.8056640625,2878.6472167969,99.761512756348" rotation="9.6452484130859" int="0" dim="0" />
        <exit pos="-2609.7607421875,107.54463195801,-65.099998474121" rotation="183.69342041016" int="0" dim="4" />
    </interior>
```

**Comment by Griffin687** [comment]
Hello,

We would like to adjust one marker:

<interior restriction="team,CLO,Official Gangs" name="ThCGetAway" >
    <entry pos="-1365.8056640625,2878.6472167969,99.761512756348" rotation="9.6452484130859" int="0" dim="0" />
    <exit pos="-2609.7607421875,107.54463195801,-65.099998474121" rotation="183.69342041016" int="0" dim="4" />
</interior>

**Comment by SAESHenry** [comment]
Will be live next server update
