### ISSUE TITLE
Organization Zero's Skin Change

### ISSUE THREAD

**Issue by DravenCG** [saesrpg/saesrpg-gang#299]
Greetings,

We would like to remove Andre skin (ID:303) from our spawn and replace it by Omyri (ID:59) with the skin shader linked below.
Link : https://www.dropbox.com/s/p9sx67q7u5itzkn/omyri-256x512.dds?dl=0
We would also like to remove the current shader from Pimp skin (ID:249)

Thank you!

**Comment by SAESHenry** [comment]
Will be live next server update
