### ISSUE TITLE
[CS] Cunning Stunts | Forum Moderation rights

### ISSUE THREAD

**Issue by iMatizZ** [saesrpg/saesrpg-gang#3]
As title says , i need forum moderation rights in Cunning Stunts section and private forums. 
Link: https://saesrpg.uk/category/163/cunning-stunts 
My profile link: https://saesrpg.uk/user/matizz
We have requested it but seems admin forgot to add me. 
Thanks 💯

**Comment by iMatizZ** [comment]
Oh sorry, ok thanks

**Comment by iMatizZ** [comment]
Yeah , i need it aswell

**Comment by saesrpg** [comment]
This is now done.
