### ISSUE TITLE
The Outfit's Changes 

### ISSUE THREAD

**Issue by Sira188** [saesrpg/saesrpg-gang#30]
Hello there , we would love to request our new changes related our organization. It's passed a lot of time since last change so here we are again. 

Base Mapping : http://www.mediafire.com/file/rffsxtfcccba9yi/The-Outfit-Base-2019.lua/file
Base Mapping's shaders : http://www.mediafire.com/folder/ybfdf3dl00i81/for_GM
Gates : https://pastebin.com/y35098Yd
Spawn point : https://pastebin.com/PvCb56qm
Markers : https://pastebin.com/L6RjxUcJ
ATM location : https://pastebin.com/pMi9tei7

We would love to keep our current interior and his shaders. Also we would love to keep our current skin's shaders. About the vehicles, I prefer to sort them in game. Thank you (kisses)

**Comment by IEDaryl** [comment]
Hey guys,

What's the current SL on gang reward changes?

Cheers.
