### ISSUE TITLE
Los Lunas Level 3 Reward Fixes

### ISSUE THREAD

**Issue by Line558** [saesrpg/saesrpg-gang#300]
We would like to add vmaff1 skin (ID:124) the skin shader linked below.
Skin Shader Link: https://www.mediafire.com/file/z0u1ir5yyfvgl4s/lunasspeed1.dds/file
Interior: https://www.mediafire.com/file/z7emlpb12sg4dip/MARKER_CODES_FIXES.txt/file
Spawn Code: https://www.mediafire.com/file/mbsyw5govsoc40j/SPAWNCODEFIXES.txt/file
we would add car spawn in our disk in base
Spray Fixed: https://mega.nz/file/TpxF2AYT#9Gyj69QYMV-M5Jvsgg2BKwuNjzjH_prEYJN26x5Jq9Y
and our (invite advert) doesnt work
give this user hq team in forum:
https://saesrpg.uk/user/speed1tn

**Comment by SAESHenry** [comment]
> give this user hq team in forum: https://saesrpg.uk/user/speed1tn


Forums requests are to be done in saesrpg-web

**Comment by SpeeD1Pro** [comment]
Spray fixed

https://mega.nz/file/fwpSiQDI#1eZqXPjYDsc1p81DQ32HxqZLUvnFPvZE73DhjZCIVOo
