### ISSUE TITLE
MIT Level 4 Reward Fixes

### ISSUE THREAD

**Issue by SOLLOZZO-SAES** [saesrpg/saesrpg-gang#301]
Hello, we would like to have those fixes : 

**Spawncode :** 
https://pastebin.com/BEFvjtFB

Please check if the parachute are here in both spawns.

_We have special attention for the AK47 of the secondary spawn, thanks._

---

124 VMAFF Moustache authorized skin : 
Model ID : 124
Model name : vmaff1
Spawn name : MIT Intervention Unit
Shader : http://system.netgate.free.fr/c/saes/mit/level4fixes/vmaff1.dds

---

⚠️ We lost the **/polight** function

and the **/TOGGLEWALK** : 

MOVE_BLINDMAN (127)

---

Thanks.
Credits goes to the same individuals as the original post.

**Comment by SAESHenry** [comment]
Will be live next server update
