### ISSUE TITLE
GSF LVL2 REQUEST

### ISSUE THREAD

**Issue by voli1** [saesrpg/saesrpg-gang#304]
Hey I would like to request our level 2 rewards

Spawn codes: ( https://www.mediafire.com/file/k7g5l68ly2xo6tk/Nouveau_document_texte.txt/file )
`<spawn id="Grove Street Family" skin="270,106" x="2485" y="-1553.6999511719" z="24.799999237061" rot="25.0025329" weapons="5,1;22,75;26,50;32,150;46,1;41,99999" description="We never leave our brother behind us we are the Grove Street Family~." r="12" g="112" b="47" restricted="gang,Grove~Street~Family" ganglevelrestriction="0" />`
Skin shader:
https://www.mediafire.com/file/mwpfcudagdd4dem/GroveFAM2.dds/file (skin)
["Grove Street Family"]={[106]={["fileName"]=GroveFAM2.dds',["textureName"]="fam2"},},
(https://i.imgur.com/xWc6JGPh.jpg)
Spray tag:
https://www.mediafire.com/file/ony4rnpfrd2cqst/SPRAY.dds/file  (spray)
Base:
https://www.mediafire.com/file/beb5e2m7wk0ffks/GSF+base.rar/file (base & shader)
Our Job:
/sell (arms)
 Togglewalk:
MOVE_GANG2
Vehicles: contact me in game plz or any hq

**Comment by SAESHenry** [comment]
Will be live next server update
