### ISSUE TITLE
HRMC - Level 2 Rewards

### ISSUE THREAD

**Issue by Franklin880** [saesrpg/saesrpg-gang#305]
Hello there, I would like to request Hell Raisers MC Level 2 rewards..
If there are any complications please contact **Wask#2072** on discord, thank you!

**Spawn Code**
`<spawn id="Hell Raisers MC" skin="100,291" x="673.65704" y="-452.71017" z="20.65293" rot="90" weapons="5,1;22,75;26,50;28,150;46,1;41,99999"
description="Hell Raisers are an outlaw motorcycle club riding through San Andreas, they are currently stated in Red County, Dillimore as the one and only charter." r="51" g="3" b="63" restricted="gang,hellraisers_mc" ganglevelrestriction="0" />`

**If the color above is not acceptable use this spawn code format:**

`<spawn id="Hell Raisers MC" skin="100,291" x="673.65704" y="-452.71017" z="20.65293" rot="90" weapons="5,1;22,75;26,50;28,150;46,1;41,99999"
description="Hell Raisers are an outlaw motorcycle club riding through San Andreas, they are currently stated in Red County, Dillimore as the one and only charter." r="88" g="73" b="73" restricted="gang,hellraisers_mc" ganglevelrestriction="0" />`

___

**Skin Shader**

`["Hell Raisers MC"]={[100]={["fileName"]=wmycr.dds',["textureName"]="wmycr"},},`

File: https://www.mediafire.com/file/f332za4a03syxqi/wmycr.dds/file

___

**Togglewalk**
MOVE_GANG1

___

**Base**
Lua: https://www.mediafire.com/file/g1e9h3pcf6afgh6/HRMC-Base.lua/file

___

**Base Shaders**
Lua: https://pastebin.com/Yg2Y74dx
Images: https://www.mediafire.com/file/1r8n6a9w75s0lkc/HRMC-Base_Shaders.rar/file

___

**Spraytag**

`["Hell Raisers MC"]="images/hrmcspray.dds"`
File: https://www.mediafire.com/file/lewpb2lbsgtkjsj/hrmcspray.dds/file
___

**Disk Location**
691.05896, -455.23514, 20.65293

___

**Job**

/sell (weapons)

___

**Vehicles**
-Towtruck
-Burrito
-Dodo
-Freeway
-Freeway
(Will be shown ingame)

**Comment by SAESHenry** [comment]
Will be live next server update

**Comment by TheMetalizer** [comment]
Vehicles sorted [Freeway, Burrito, Dodo (you requested 2 above the limit)]
