### ISSUE TITLE
Royal Flush lvl 1 rewards

### ISSUE THREAD

**Issue by KingNevs** [saesrpg/saesrpg-gang#307]
2 gang vehicles:
Jester and Stratum. 
Colour:  Primary: #E0A2A2          Secondary: #E0A2A2

Parked next to the other cars in our base "Big smoke ordered a pizza here".

The base: 
https://imgur.com/UkYcQmL

----------------------------------------------------------------------------------------------------------------------

A private role in SAES Gang Management named "Royal Flush" colored #E0A2A2

Gang HQs:
Nevs#2471
Thamond#9353
Villain#0552

----------------------------------------------------------------------------------------------------------------------

A private forum named "Royal Flush" and a private forum attached to it.

Admins of the group should be:
https://saesrpg.uk/user/nevs
https://saesrpg.uk/user/thamond
https://saesrpg.uk/user/villain

We would like our main topic and media archive to be moved from where it currently is, and to the subcategories section in gangs next to our private forum.

Main topic:
https://saesrpg.uk/topic/25248/royal-flush?page=1

Media Archive:
https://saesrpg.uk/topic/25249/royal-flush-media-archive

**Comment by TheMetalizer** [comment]
Please make a new request under saes-web for the forum rewards.

The rest is sorted.
