### ISSUE TITLE
Hell Soldiers | Base change

### ISSUE THREAD

**Issue by kockata666** [saesrpg/saesrpg-gang#308]
Base: https://pastebin.com/F5AJuvWd
Base shaders: https://pastebin.com/zQuu0jGL and https://www.mediafire.com/file/upkvrp06eknmjc1/HSDDS.rar/file

Spawn: https://pastebin.com/sN7TzvQ9
Gate: https://pastebin.com/vKwZhCLr

Interior marker: https://pastebin.com/W3vXY1i0
Interior map: http://www.mediafire.com/file/9jslthlxhxy78vz/HSinterior.lua/file

**Comment by SAESHenry** [comment]
Will be live next server update
