### ISSUE TITLE
Remove gang safe - UE

### ISSUE THREAD

**Issue by UE-Arctic** [saesrpg/saesrpg-gang#317]
We'd like our gang safe removed until further notice.

Thanks

**Comment by UE-Arctic** [comment]
if you can send me the coords for the safe then please do, or note them as a comment here that'd be perfect.

**Comment by SScorpyo** [comment]
```xml
<safe id="Underground Empire" x="2155.5" y="1749.95" z="23.70" rot="0" restricted="gang,UndergroundEmpire"/>
```
