### ISSUE TITLE
ICE BASE IS BAD

### ISSUE THREAD

**Issue by IEDaryl** [saesrpg/saesrpg-gang#32]
HELLO ALL,

THE ICE BASE IS BAD

IT IS UGLY AND IT MAKES ALL OF THEIR CARS GO ON THE ROAD

THIS IS BAD

IT HURTS MY CAR

THEN MY CAR HURTS ME

WHO WILL MAKE RIGHT THIS WRONG

THANK IN ADVANCE

DARYL)))

**Comment by IEDaryl** [comment]
HELLO IT ME AGEN,

I CAN PROVIDE SHOTS OF MY SCREEN OF THIS

THANKS,

)

**Comment by ghost** [comment]
Hello this is call-center writing from Bangladesh India.

We have special offer for you to secure area.
We give now 1 free punch instead of nothing!

I FEEL BAD FOR CAR SIR

CAR FEELS BAD FOR YOU SIR

jokes aside,

They will move asap to a more less stressed area.

**Comment by Kare0015** [comment]
![mta-screen_2019-02-22_12-10-12](https://user-images.githubusercontent.com/22007136/53253904-900f7c00-36c2-11e9-8239-c2980308770a.png)


SEND HELP PLS

**Comment by MrMedEra** [comment]
The answer was clear beside bone's disabilities in explaining imma make it more clear xD.
The base will be moved/removed from there indeed be patient guys 😎
