### ISSUE TITLE
Navy Malistrip level 5 rewards request.

### ISSUE THREAD

**Issue by emramirez23** [saesrpg/saesrpg-gang#324]
I would like to update skins, weapons, jobs, and the ATM for now.

< spawn id="Navy Malistrip Captain" skin="176" x="2001.58875" y="2925.12744" z="49.61719" rot="90" weapons="10,1;24,250;27,250;29,350;31,450;34,150;16,10;46,1;41,4000" description="Captains of the Navy Malistrip." r="92" g="125" b="108" restricted="gang,Navy_Malistrip" ganglevelrestriction="5"/ >

This skin shader is placed here:

https://www.mediafire.com/file/e4xev6lmbvxm6ur/BMYBAR.dds/file 

< spawn id="Navy Malistrip" skin="230,195,19" x="2001.58875" y="2925.12744" z="49.61719" rot="90" weapons="10,1;22,250;27,250;29,350;31,450;34,150;16,10;46,1;41,4000" description="Somalian pirates who've decided to discover beyond the horizon, the new captains of San Andreas." r="92" g="125" b="108" restricted="gang,Navy_Malistrip" ganglevelrestriction="0"/ >

The ID 19 Skin shader is placed here:

https://www.mediafire.com/file/s9bmuar3wu7hzr1/NavM.dds/file

(We would like to add Double Colt in the main spawn "Navy Malistrip", it's added in the code with the ID 22)

The remaining shaders are already uploaded ingame.

ATM position: 2034.8889160156,2981.2158203125,17.748962402344

*Jobs (in both spawns please)
weapons: /sell
drugs: /selldrugs

**Comment by TheMetalizer** [comment]
✅

**Comment by emramirez23** [comment]
😁
