### ISSUE TITLE
B~B Skin change

### ISSUE THREAD

**Issue by Ahmed-khayry** [saesrpg/saesrpg-gang#325]
Hello,
We would like to remove "vmaff2" (ID:125) from our spawn and replace it by "swmotr5" (ID:230) with the skin shader linked below:
https://www.mediafire.com/file/2tioecpvflywaox/swmotr5.dds/file

Could you add the shader "swmotr5" (ID:230) for veteran spawn as a second skin with the normal spawn skin.
we want to remove B~B Veteran normal spawn skin "vmaff3" (ID:126) and replace it by "triadb" (ID:118).

**Comment by TheMetalizer** [comment]
Refer to your GM Discord channel for the issues regarding this request

**Comment by TheMetalizer** [comment]
✅
