### ISSUE TITLE
FBI Spawn Changes

### ISSUE THREAD

**Issue by IEDaryl** [saesrpg/saesrpg-gang#326]
[FBI Changes.txt](https://github.com/saesrpg/saesrpg-gang/files/6680988/FBI.Changes.txt)
GitHub does not support .dds so the shader is in the HQ channel for FBI on the GM discord

**Comment by IEDaryl** [comment]
Updated changes
[FBI Changes.txt](https://github.com/saesrpg/saesrpg-gang/files/6681927/FBI.Changes.txt)

**Comment by TheMetalizer** [comment]
✅
