### ISSUE TITLE
Mongols MC | Level 2 Rewards

### ISSUE THREAD

**Issue by Mondea** [saesrpg/saesrpg-gang#327]
# **Skins/Spawns**

**Name:** Claude, vwmycr
**Skin ID:** 299 , 181
**Download:** https://www.mediafire.com/file/2zor9k9iygw5gkp/MMC-base.rar/file
**Spawn:**
`<spawn id="Mongols MC" skin="181,299" x="-2150.16" y="-232.43" z="35.36" rot="0" weapons="5,1;22,75;26,50;32,150;46,1;41,99999" 
description="Notorious outlaw 1%er motorcycle club, The Mongols MC." r="27" g="27" b="27" restricted="gang,Mongols_MC" ganglevelrestriction="0" />
`
**Skin Shader:** 
For Claude skin
`
["Mongols MC"]={
        [299]={["fileName"]='claude.dds',["textureName"]="claude"
},
`

---

# **Base**
**LUA/MAP download:** https://www.mediafire.com/file/ac5hhv0t9gov0wz/MMC-base%25282%2529.rar/file
**Shaders download:** https://www.mediafire.com/file/9w3eqzqongvt9j6/Shaders_dds.rar/file

**Warp markers:** 
`<interior restriction="gang,Mongols_MC" name="ClubhouseEntranceIn">
    <entry pos="-2138.40405, -235.22163, 35.36875" rotation="180" int="0" dim="0" />
    <exit pos="-2123.90649, -247.14171, 35.80781" rotation="180" int="0" dim="0" />
</interior>`

`<interior restriction="gang,Mongols_MC" name="ClubhouseEntranceOut">
    <entry pos="-2123.90649, -247.14171, 35.80781"  rotation="0" int="0" dim="0" />
    <exit pos="-2138.40405, -235.22163, 35.36875" rotation="0" int="0" dim="0" />
</interior>`

`<interior restriction="gang,Mongols_MC" name="ChurchEntranceIn">
    <entry pos="-2134.06714, -264.25497, 35.80781" rotation="270" int="0" dim="0" />
    <exit pos="-2112.86987, -229.77499, 23.82031" rotation="0" int="0" dim="352" />
</interior>`

`<interior restriction="gang,Mongols_MC" name="ChurchEntranceOut">
    <entry pos="-2112.86987, -229.77499, 23.82031"rotation="180" int="0" dim="0" />
    <exit pos="-2134.06714, -264.25497, 35.80781" rotation="90" int="0" dim="352" />
</interior>`

**Base Ped:**
`{model = 257, x = -2115.288, y = -262.261, z = 36.125, rot = 180, animBlock = "STRIP", animName = "STR_C2", dim = 0, int = 0, weapon = 0},`

**LUA Loop:** https://pastebin.com/HYCN0uBS
**Generate LUA:** https://pastebin.com/bqPgMf25

---

# **Spray**
**Download:** https://www.mediafire.com/file/iol38bldhijddk4/MongolsSpray.dds/file

---

# **Disk**
**Coordinates:**
x = -2158.38
y= 235.61
z= 35.36

---

# **Job**
Arms dealer

---

# **Vehicles**
Shamal, Picador, Heli, Burito, Freeway

**Comment by TheMetalizer** [comment]
Refer to your GM Discord channel for the issues regarding this request

**Comment by Mondea** [comment]
Issue fixed

**Comment by TheMetalizer** [comment]
✅
