### ISSUE TITLE
Bloodz - Level 2 Rewards Request 

### ISSUE THREAD

**Issue by anxhelo00** [saesrpg/saesrpg-gang#328]
Hello, we would like to request level 2 rewards.

**-- SPAWN --**

 `<spawn id="BloodZ" skin="102,19" x="644.20001220703" y="-1141.0999755859" z="45.5" rot="305.586639" weapons="1,1;22,75;25,50;28,150;46,1;41,5000" description="BloodZ, street gang based in Los Santos that is involved in drugs, theft and murder, among other criminal activities." r="76" g="0" b="0" restricted="gang,BloodZ~" ganglevelrestriction="0" />`

**-- GANG BASE --**

Address:  Bosch Residence 

Base > https://www.mediafire.com/file/kkllc9uzd2zhgz5/bzbase.lua/file

Shaders > https://www.mediafire.com/folder/2ujw1w1xb7wne/Bloodz

**-- SKIN SHADER --**

`['BloodZ']={ [102]={['fileName']='bloodz1.dds',['textureName']='ballas1'}, },`

Skin : 102 

http://www.mediafire.com/file/ka145724uvz5lgl/bloodz1.dds/file

**-- SPRAY TAG --**

https://www.mediafire.com/file/inifuzk2e4q0s47/bzspray.dds/file

**-- VEHICLES --**

Savanna, Stratum, Damaged Glendale, Sultan, Maverick
Primary Color: #C20000
Secondary Color: #C20000
Upgrades: 10x Nitro

**--EXTRA--**
Ability to sell drugs.
Ability to take a part in bank robberies and turf wars.
Our gang topic pinned on the forums.
MOVE_GANG1 walking style.

**Comment by TheMetalizer** [comment]
✅
