### ISSUE TITLE
Hell Soldiers levan 5 rewards

### ISSUE THREAD

**Issue by candi1312** [saesrpg/saesrpg-gang#329]
If there are some kind of problems with the level 5 reward request, please contact Henry or Petrow. About new vehicles, Petrow will contact someone.

Base and skin shaders will stay the same.

Base fix:
https://pastebin.com/q2RKawVf

New gate for exterior:
https://pastebin.com/XFDPGL1d

Spawn new guns:
https://pastebin.com/JNjG1YaG

In there, I added dual colts for both lines, just mentioning it here too, we want both spawns with dual colts
Also our 2nd job is arms dealing. /sell ability for both spawns and keep drugs selling ability. /sell for drugs and /sellarms for arms. No idea how it is but drug selling has to be first what we sell

ATM position: 1057.6021728516,1299.1285400391,10.8203125

**Comment by TheMetalizer** [comment]
✅
