### ISSUE TITLE
Defence Intelligence Agency - Level 2 Rewards

### ISSUE THREAD

**Issue by JukyPlatinium** [saesrpg/saesrpg-gang#335]
We'd like to change our PD spawn from BC PD to LV PD Firstly
https://pastebin.com/dVZ7fBVe
______________________________________________________________________________
For our second spawn
https://pastebin.com/UMXq1NwY
Base File & Lua/Shaders:

["images/dialogo.dds"]={"heat_03",},
["images/dia1.dds"]={"laglaswall1","fitzwallvgn2_256","fitzwallvgn3_256","vgsclubwall08_128","ws_rottenwall","ws_breezeblocks",bluapartwall1_256","helipad_grey1",},
["images/wt.dds"]={"cj_painting22",},
["images/ws.dds"]={"cj_painting14",},
["images/rz.dds"]={"cj_painting5",},

Cars:
Police Sultan / Police Buffalo / FBI Rancher / Dodo / Heli
All at DIA Base

**Comment by TheMetalizer** [comment]
Refer to your GM channel regarding the issues of this request
