### ISSUE TITLE
Royal Flush lvl 3 rewards

### ISSUE THREAD

**Issue by KingNevs** [saesrpg/saesrpg-gang#337]
If there are any questions or issues with the request dont hesitate to contact Nevs#2471 on discord.

-----------------------------------------------------------------------------------------------------------------

Spawn code:
https://pastebin.com/t7NM8Mwm

-----------------------------------------------------------------------------------------------------------------

**Mapping**

Base:
https://www.mediafire.com/folder/1vbxwov7j0nix/RF_Base

Interior:
https://www.mediafire.com/folder/h9aqwwnbe8xzp/RF_Interior

Shaders:
https://pastebin.com/G9T42v50

Pics:
https://www.mediafire.com/folder/nikw3ctzmocfb/Pics_Shaders

Gate: https://pastebin.com/9KBvYYjz

Markers:
https://pastebin.com/vzieaT9s 

-----------------------------------------------------------------------------------------------------------------
**Skins**

Unshaded skin
Skin 263

Shaded skins
Skin 1:
["Royal Flush"]={[186]={["fileName"]=RF186.dds',["textureName"]="somyri"},},

dds file skin 186: 
https://mega.nz/file/30xFiIqR#KncjAUkEeFy7QSvvQsaRRbylvLMcCSDLkQIFfCQ-Ql0
Texture name: somyri

Spawn: Royal Flush

Model ID: 186

Skin 2:

["Royal Flush"]={[44]={["fileName"]=RF44.dds',["textureName"]="hmost"},},

dds file skin 44: 
https://mega.nz/file/bto31ApI#J2hCBOx4pcaVI9e_a_uXGqFoQwQJkW6B2NgtbeRA_-Q

Texture name: hmost

Spawn: Royal_Flush

Model ID: 44

-----------------------------------------------------------------------------------------------------------------

**Savedisk**

Next to our elevator in the garage - an HQ can show you when the rewards are being sorted.

-----------------------------------------------------------------------------------------------------------------

**Vehicles**
Picador
Jester
Damaged Glendale

**Comment by TheMetalizer** [comment]
✅
