### ISSUE TITLE
Hell Soldiers || Skin changes

### ISSUE THREAD

**Issue by Petrow2** [saesrpg/saesrpg-gang#338]
Hello, we would like to add shader for Hell Soldiers skin id 102 with this one: https://www.mediafire.com/folder/x3etutbq00lrk/ballas1

We would also like to add a second skin to the spawn Hell Soldiers OG which is the following: Maddogg (ID297)
 https://www.mediafire.com/folder/jdkh2idqt79np/maddogg

Also we would like to change double colt to deagle for both spawns

**Comment by TheMetalizer** [comment]
Refer to your GM channel regarding the issues of this request
