### ISSUE TITLE
The Company - Base - Skin - Spawn Changes

### ISSUE THREAD

**Issue by Blooooooooooo** [saesrpg/saesrpg-gang#342]
### **BASE CHANGES**

**ThC Exterior .lua ----->** https://pastebin.com/B9jhJnUS  (-1987.94226, 486.98593, 35.17188 **Coordinates incase if you want to view or w/e**) 

**ThC Interior .lua ----->** https://pastebin.com/wYGU5Qqs ( **Interior:** 12, -1704.06396, 515.95514, 2922.59204 **Coordinates incase if you want to view or w/e**)

**ThC Gates ----->** https://pastebin.com/FffKTi7g

**ThC Markers** -----> https://pastebin.com/RkcpzJLZ

**ThC Exterior Shader xml** -----> https://pastebin.com/KUTcvZ1R

**ThC Exterior Shader .lua** -----> https://pastebin.com/JtMufYv8
 
**ThC Interior Shader xml** -----> https://pastebin.com/jq9NTJ8W

**ThC Interior Shader .lua** -----> https://pastebin.com/P4M02kyG

**All shader textures can be found in both formats ( PNG & DDS) on following link,** https://www.mediafire.com/file/de7l2a4whw77xqx/ThCShaders.zip/file

Vehicle marker **will be forwarded to Terry** via Discord

**ATM Location:** -2060.099609375,434.79998779297,139.39999389648 ROT: 0,0,180

---

### **SKIN & SPAWN CHANGES**

```
<spawn id="The Company" skin="120,93,186" x="-2029.56555" y="439.60742" z="139.74211" rot="270" weapons="2,1;24,250;27,250;28,350;31,450;34,150;16,10;46,1;41,5000"
description="No details are given. Things are more complicated than you think, you know. People refer to us as The Company." r="157" g="156" b="156" restricted="gang,The_Company" ganglevelrestriction="0" />
```

```
<spawn id="The Company Archon" skin="120,70,186" x="-2029.56555" y="439.60742" z="139.74211" rot="1270" weapons="2,1;24,250;27,250;28,350;31,450;34,150;16,10;46,1;41,5000"
description="No details are given. Things are more complicated than you think, you know. People refer to us as The Company." r="157" g="156" b="156" restricted="gang,The_Company" ganglevelrestriction="7" />
```

```
["The Company"]={
    [93]={['fileName']='THC_1_1.dds',['textureName']='wfyst'},    
    [120]={['fileName']='THC3.dds',['textureName']='triboss'},
    [186]={['fileName']='thc31.dds',['textureName']='somyri'},
},
["The Company Archon"]={
    [70]={['fileName']='THC2.dds',['textureName']='wmosci'},
    [120]={['fileName']='THC3.dds',['textureName']='triboss'},
    [186]={['fileName']='thc31.dds',['textureName']='somyri'},
}
```

**Skin Shaders in ZIP** -----> https://www.mediafire.com/file/kz4gbznmtvek28d/ThCSkins.zip/file

**Comment by SScorpyo** [comment]
Live
