### ISSUE TITLE
ICE Base Change (Many Problems with our Current base)

### ISSUE THREAD

**Issue by 00Sam00** [saesrpg/saesrpg-gang#35]
Hello,
Because of some issues with our current base, we decided to move to a new Location.
Here are the following Requests:

**SPAWN**

Link to our spawn codes here: https://pastebin.com/xyF2kyrB

**SKIN SHADERS**

We like to change 1 Skin Shaders. The rest please leave them how they was before!

Spawn name: ICE Special Unit
Skin name: somori
Skin id: 228
Model: https://ufile.io/sav1m

**MARKER & GATE CODES**

Here is the link for the Gate Codes: https://pastebin.com/hFWDPcGd
Here is the link for the Marker Codes: https://pastebin.com/9qK7jb2p

**BASE & INTERIOR FILES**

Link for Mapped Base: https://ufile.io/fwgnd (Note: Please make sure the windows don't break) (UPDATED)
Link for Mapped Interior: https://ufile.io/l36kk 

**OBJECT SHADERS FOR BASE & INTERIOR**

Link to Base Shaders: https://ufile.io/879cw
Link to Interior Shaders: https://ufile.io/2t0pk 

**NPCS CODES**

Link to the NPCS Codes: https://pastebin.com/81f6LF6J

**WALKING STYLE**

We want to request a walking style for ICE here the: walking style is id 125. (Edited)

**EXTRAS**

And also we want to request the command: /polight
And please don't forget to leave: /deploystinger

**Comment by MrMedEra** [comment]
This shall be done fast as its a public request 😂

**Comment by 00Sam00** [comment]
NPCS Are in the wrong skin id, also in interior are missing Peds. I did not make mistake in the codes. Please could you fix that? https://pastebin.com/81f6LF6J
