### ISSUE TITLE
O spawn updates

### ISSUE THREAD

**Issue by SAES-Jay** [saesrpg/saesrpg-gang#354]
spawn id="The Outfit" skin="120,150,240"
spawn id="The Outfit Lynchpin" skin="186,150,120"

Here are new shaders to go with.
https://www.mediafire.com/file/teewgxsqlw0m1hi/Outfit_Skins_-_DDS_and_PNG.rar/file

We would also like to swap out the MP5 and replace with the tec9 for "The Outfit" spawn.

**Comment by SScorpyo** [comment]
Sorted
