### ISSUE TITLE
SSB Level 2 Rewards

### ISSUE THREAD

**Issue by blizzardOG99** [saesrpg/saesrpg-gang#367]
Base Map Lua: https://pastebin.com/JyF2hefv

Shaders Files: https://easyupload.io/pyyfcd

Base Shader Code: https://pastebin.com/pYuw7Dg3

---

SSB Spawn Code: https://pastebin.com/jsDfwcJg

Skin Shader file: https://i.imgur.com/9GfdcZ3.png

Skin ID 85, texture name: vwfypro

Job requested: selldrugs

---

Spray tag: https://easyupload.io/za0qvb

Preview: https://i.imgur.com/mj8VmaO.png

---

Madd Dogg issue: https://github.com/saesrpg/saesrpg/issues/424

---

We would also like to request the removal of any main chat filters associated with the words "SSB" and "ssb"

---

Vehichles requested (for a total of 5)

1 Maverick
1 Infernus
1 NRG-500

We would also like to switch the current "Elegant" vehicle for a Huntley

**Comment by SAESKain** [comment]
- Roof/some exterior walls need flipping to prevent camera clipping
