### ISSUE TITLE
Ghost~Triad ~ Level 3 Rewards

### ISSUE THREAD

**Issue by Sharlock016** [saesrpg/saesrpg-gang#369]
- **Spawn:**
`<spawn id="Ghost~Triad" skin="123,49,226" x="2758.01099" y="-1953.14905" z="13.54992" rot="0" weapons="1,1;24,125;26,100;30,200;28,200;46,1;41,5000"
description=''We count you out before you figure us out!'' r="115" g="46" b="62" restricted="gang,GhostTriad" ganglevelrestriction="0" />`

- **BASE:**
EXTERIOR (lua): https://www.mediafire.com/file/5ce06f1gnjuxi5b/gtlvl3.lua/file
[set Dim:402] INTERIOR (lua): https://www.mediafire.com/file/n2ik527c9s0v9nl/gtinterior.lua/file
- **BASE SHADERS:**
DDS: https://www.mediafire.com/folder/f2ecut4xiqzxh/GTshaders
CODE: https://pastebin.pl/view/98a7373e
- **MARKERS:**
CODE: https://pastebin.pl/view/93ae5cdb
- **GATE:**
CODE: https://pastebin.pl/view/67ef1748

- **SKINS & SHADERS**
`["Ghost~Triad"]={[226]={["fileName"]=SOFYST.dds',["textureName"]="sofyst"},},`
FILE: https://www.mediafire.com/file/o3zleq4bdc5nkms/SOFYST.dds/file (new skin)

- **TOGGLEWALK**
MOVE_GANG1

- **SPRAY TAG**
DDS: https://www.mediafire.com/file/i3i7jwlfqg3n18x/GTSPRAY.dds/file (new spray)

- **JOB**
Drug Dealer

- **VEHICLES**
Maverick | Savanna|Picador|Shamal|Dodo|Sabre|Cheetah
Modifications: Nitro x10 | V8 | AWD
Primary Color: #693645
Secondary Color: #693645

**Ghost~Triad's HQ Team**

**Comment by SAESKain** [comment]
- All ready for push
- Unshadered skin removed due to only 2 skins allowed at level 3
