### ISSUE TITLE
S.W.A.T. - Updates

### ISSUE THREAD

**Issue by Niceez** [saesrpg/saesrpg-gang#370]
**Base .lua (interior, exterior):** https://drive.google.com/drive/folders/1z2WosOjGgKsC0t0diSPPNA3TsI6fPQTQ?usp=sharing
**Base shaders:** https://drive.google.com/drive/folders/1UGs1_Si135-Ih8HpKy_9-PAPdQs2U4xm?usp=sharing
**Exterior gates:** https://pastebin.com/wvQd3L6U
**Interior gates:** https://pastebin.com/3FZHqq0q
**Base markers**: https://pastebin.com/Uk2Rn76M

**SWAT Spawn code:** https://pastebin.com/NJ7wpWe0
**Skin shaders:**

1. https://imgur.com/a/pvpvuO7 (ID 285, model swat) - Only on S.W.A.T. Offficer 
2. https://imgur.com/a/HaQPJvg (ID 285, model swat) - Only on S.W.A.T. Tactical Paramedic
3. https://imgur.com/a/iguStI3 (ID 98, model wmyri) - Only on S.W.A.T. Officer
4. https://imgur.com/a/Ln4RjDi (ID 13, model bfyst) -  On S.W.A.T. Officer and S.W.A.T. Tactical Paramedic

**Jobs:**

1. Dispatcher, Speedtrap - for S.W.A.T. Officer, S.W.A.T. Tactical Paramedic
2. Speedtrap - for S.W.A.T. Cadet

Vehicles locations will be shown in game.
ATM location will be shown in game.

**Comment by Niceez** [comment]
Same files from "Base shaders' link, but in pastebin if it simplifies your job

Exterior Shaders in Lua -----> https://pastebin.com/a8HCxUGC
Interior Shaders in Lua -----> https://pastebin.com/j2tBS96M
Shaders XML -----> https://pastebin.com/v0p7S4GK
SWAT Shaders in DDS -----> https://www.mediafire.com/file/9w46hw73l20y1o1/swatdds.rar/file

**Comment by Niceez** [comment]
x="1609.02" y="-1190.1" z="6.5" rot="270"  - ATM Location

Also, if it's possible, we would like to request files of our current interior.

**Comment by Niceez** [comment]
Skin shaders (dds)

https://drive.google.com/drive/folders/18aGqaQPnrN1aZWI8R5iMqVEjZZK4Iej5?usp=sharing (ID 285, model swat) - Only on S.W.A.T. Offficer
https://drive.google.com/drive/folders/1smDt6d9u4bK1AUbkXkWk4b0yGOCUq8J0?usp=sharing (ID 285, model swat) - Only on S.W.A.T. Tactical Paramedic
https://drive.google.com/drive/folders/143zUNpToy0YY1EZMsa1b_gusojD5DlYi?usp=sharing (ID 98, model wmyri) - Only on S.W.A.T. Officer
https://drive.google.com/drive/folders/1w0EMJwwVdpexdUw-ry57m5hAE9bSmoYZ?usp=sharing (ID 13, model bfyst) - On S.W.A.T. Officer and S.W.A.T. Tactical Paramedic

**Comment by SAESKain** [comment]
Shaders are required to be dds and no more than 65kb each
