### ISSUE TITLE
SSB level 3 base updates

### ISSUE THREAD

**Issue by Yannick-DG** [saesrpg/saesrpg-gang#378]
Hi guys,

doing a request in the name of SSB. I'll have Mellow approve the request as SSB Vice leader for this request. Below is a ZIP with all the information, for questions or issues please reach out to me on Discord Yannick#1936.

[SSB.zip](https://github.com/saesrpg/saesrpg-gang/files/8836236/SSB.zip)

I also need a car teleport marker added like AA has with their garage. Just no clue if that's done by the marker script or not. Here I'll dump the coordinates atleast

Marker outside garage (X,Y,Z): `-1643.53101, 1305.55408, 7.02745`
Rotation for when a car comes out (Rotation Z): `133`

Marker inside garage (X,Y,Z): `-1631.65686, 1317.24255, 7.15354`
Rotation for when a car comes in (Rotation Z): `313.55`

Marker should be restricted to `class,South Side Blazers`

if possible, please test if the garage marker works fine and that the cars don't catch damage.

Thanks in advance!

**Comment by hellamello** [comment]
Hello, I approve this request as SSB HQ

**Comment by Yannick-DG** [comment]
As discussed with Scorpyo. You can remove Bobo's face as it wasn't allowed. All base textures are just for the exterior and the car marker is due to a barrier being in between the garage, hence a teleport is required.
