### ISSUE TITLE
ICE HQ Private Forum

### ISSUE THREAD

**Issue by 00Sam00** [saesrpg/saesrpg-gang#39]
Hello,
we like to request a HQ forum within our ICE Private Forum.

Moderators:
https://saesrpg.uk/user/sam
https://saesrpg.uk/user/james

Thank you

**Comment by ghost** [comment]
Check out this repository for that request https://github.com/saesrpg/saesrpg-web

**Comment by 00Sam00** [comment]
Ah sorry okay ( delete it please)
