### ISSUE TITLE
MS13 LVL 1 Rewards

### ISSUE THREAD

**Issue by SpeeD1Pro** [saesrpg/saesrpg-gang#391]
Greetings, we'd like to claim our level 1 rewards.

2 Vehicles:

Greenwood and voodoo (V8 & AWD)
Color: #80002a
Base location: LS El Corona Street
-----------------------------------------------------------------------------------------------
A role & a private channel within "SAES Gang Management" discord server
Role Name: Mara Salvatrucha 13
Role Color: FFAA08
MS13 HQ's:

SPEED#9912
BlaZe#3808
Georges#7412
MSKV_05#5045
-----------------------------------------------------------------------------------------------
Private Forum in saesrpg.uk with Mara Salvatrucha 13 name
HQ's: SpeeD1Tn/VeX

**Comment by TheMetalizer** [comment]
Discord channel and vehicles were taken care of.

Please make a seperate issue for the website requests under saesrpg-web section.
