### ISSUE TITLE
The Company - Updates

### ISSUE THREAD

**Issue by cooIguy** [saesrpg/saesrpg-gang#393]
Hi, I am posting this on behalf of ThC. We have reshadered one of our skins and changed our 2nd spawn's name.
- **SPAWN** 
[Click here](https://pastebin.com/aaug4umb)

- **SKIN**
["The Company Mercenary"]={[98]={["fileName"]=THC4.dds',["textureName"]="wmyri"},},
[Click here](https://cdn.discordapp.com/attachments/677175903222235186/1010646366915141632/THC4.dds)

**Comment by JohnnyEnglish24** [comment]
Accepted
