### ISSUE TITLE
DE fixes 

### ISSUE THREAD

**Issue by SScorpyo** [saesrpg/saesrpg-gang#4]
Hello
The spawn that got added yesterday 'Seaman Recruit' somehow got bugged and removed, we would like to get that fixed please
Also change the walkstyle to 69 ( if possible ) 
And finally, delete General Of The Army spawn in bone county, and put the moded skin in the Military Commander spawn
Thank you

**Comment by SScorpyo** [comment]
Also remove MCC skin shader since you forgot about it

**Comment by SScorpyo** [comment]
Since there was an issue with peds skin shader, a timer needs to be added for some reason
So replace this `triggerEvent("onPlayerSpawn",depeds,depeds)` with this `setTimer(function() triggerEvent("onPlayerSpawn",depeds,depeds) end, 500, 1)`

**Comment by SScorpyo** [comment]
Change the trigger for ```<!-- Naval Dock Gate  -->``` to:
 ```	<trigger x="-1347.1" y="426.058" z="-4.5" radius="30" height="10" movetime="1200" allowed="team,Desert Eagles" >```

**Comment by SAESKain** [comment]
In regards to the peds skinshader, it's not a timer that's the issue. It's probably because skinshaders were restarted after naval base so consequently all shaders reset. As long as naval base is restarted afterwards, it's fine.
