### ISSUE TITLE
Black Bullets skinshader re-addition & new billboard

### ISSUE THREAD

**Issue by blizzardOG99** [saesrpg/saesrpg-gang#401]
I am requesting, on the behalf of B~B HQ, a re-addition of a skinshader that has, for some mystical reasons, gone missing ever since we switched the base.

Skin shader file: https://i.imgur.com/Om60lU1.png

Skin ID: 120 ; Texture name: triboss

The skin is on the normal member spawn, "Black~Bullets"

-------------------------------------

We are also requesting a new billboard in-game

DDS file: https://www.mediafire.com/file/f5kqqdg4r977zlu/BB+BILL+DDS.dds/file

PNG Image: https://i.ibb.co/ZMNVnyM/59807253-dcc93380-92ff-11e9-844d-a5b06150b029.png

**Comment by steven517** [comment]
this is now live
