### ISSUE TITLE
NPCS Fixes in ICE Base

### ISSUE THREAD

**Issue by 00Sam00** [saesrpg/saesrpg-gang#41]
Hello,
we like to fix our Peds in ICE Base. 
The Position of the Peds are good, the problem is:
** All Peds are in the skin id 228, they should be different as they are written in Pastebin **
** Also make sure to give them the Weapon ID, is also written in Pastebin **
** We are Missing Peds in Interior **

NPCS Codes: https://pastebin.com/81f6LF6J

**Comment by ghost** [comment]
The NPC codes are the same as the pastebin one. If you want them changed provide the correct codes.

**Comment by 00Sam00** [comment]
Sorry but the pastebin codes are right I put the skin id number 285. If you look you can see it, we have at our current base skin number 228 but that's wrong I did not put this number in the codes. Also I have added peds inside the interior we do not have any peds inside in interior.

**Comment by ghost** [comment]
Oh right, Skin ID 258 has the dog mod on it so they can't be used as NPC. Sorry for the confusion.

**Comment by 00Sam00** [comment]
I'm sorry I saw now that it was my fauld I added 258 instead 285. I fixed the pastebin code now it should be skin id 285.
