### ISSUE TITLE
DezZolation Island

### ISSUE THREAD

**Issue by IEDaryl** [saesrpg/saesrpg-gang#43]
This vanity project has run its course. Can you encorporate this into the San Fierro spawn panel.

If you insist on keeping the BoM spawn please put it under civilian and remove the black colour, it's currently clashing with like 4 groups.

This group also definitely does not fit the standards we have for groups.

**Comment by ghost** [comment]
"Dezolation island will be removed from spawn screen and the Brother spawn will be shown at SF civilian at same spawn coords
