### ISSUE TITLE
ICE lvl 4 Rewards Request 

### ISSUE THREAD

**Issue by 00Sam00** [saesrpg/saesrpg-gang#5]
Hello,
i moved the new request into the new bug tracker!
Here are our following requests for level 4:

______________________________________________________________________________________

**SPAWN**

Link to our spawn codes here: https://pastebin.com/GsUa9EpL

______________________________________________________________________________________

**SKIN SHADERS**

We like to change our 3 Skin Shaders.

Spawn name: ICE Agent 
Skin name: swat
Skin id: 285 
Model: https://ufile.io/7v7im

Spawn name: ICE Agent 
Skin name: lapd1
Skin id: 280 
Model: https://ufile.io/13yc4

Spawn name: ICE Special Unit
Skin name: somori
Skin id: 228
Model: https://ufile.io/zyhrj

______________________________________________________________________________________

**MARKER & GATE CODES**

Here is the link for the Gate Codes: https://pastebin.com/duHJbbyX
Here is the link for the Marker Codes: https://pastebin.com/8yrrzVhG

______________________________________________________________________________________

**BASE & INTERIOR FILES**

Link for Mapped Base: https://ufile.io/r7eqj (Note: Please make sure the windows don't break) (Updated)
Link for Mapped Interior: https://ufile.io/9gdfh (Updated)

______________________________________________________________________________________

**OBJECT SHADERS FOR BASE & INTERIOR**

Link to Base Shaders: https://ufile.io/h1dwm (UPDATED)
Link to Interior Shaders: https://ufile.io/8v11h (UPDATED)

_______________________________________________________________________________________

**NPCS CODES**

Link to the NPCS Codes: https://pastebin.com/kR3sLNJW
_______________________________________________________________________________________

**WALKING STYLE**

We want to request a walking style for ICE here is the id: MOVE_SWAT 128

_______________________________________________________________________________________

**EXTRAS**

And also we want to request the command: /polight
And please don't forget to leave: /deploystinger

**Comment by MrMedEra** [comment]
```We like to change our 4 Skin Shaders.```
As lvl 4 you can just request 3 as you can see here *https://saesrpg.uk/topic/5633/shader-size-limits*

**Comment by 00Sam00** [comment]
WoW now we gonna comment here every single think? I think it should be only able to comment for admins not for regular users. In the old bug tracker this never happened. 

BTW this is added now new this should have nothing to do with us. This was never written in rewards or request that we can make only 3 skin shaders. Kain added it before 4 hours..

**Comment by MrMedEra** [comment]
Yes and thats why i'm commenting here with my limited powers trying to help in the smallest details, and i think comments cant be disabled. 
There is a time for everything

**Comment by SAESKain** [comment]
Base shaders must be dds, multiples of 4 and comply by the shader rules found here:

Base Shaders

1024 x 1024 / 512kb - All base shaders added together must be <= to this (Either 512kb or all must fit in a 1024 x 1024 window, both are equivalent)

**Comment by 00Sam00** [comment]
Interior and Exterior Shaders link Updated!

**Comment by SAESKain** [comment]
Your exterior mapping is 8kb over
Your interior mapping is 1kb over

**Comment by 00Sam00** [comment]
exterior and interior link Updated!

**Comment by SAESKain** [comment]
Your interior hasn't changed at all

**Comment by 00Sam00** [comment]
Yes the interior is changed.
