### ISSUE TITLE
Remove the Bus waiting station infront of FBI base

### ISSUE THREAD

**Issue by Qweezy331** [saesrpg/saesrpg-gang#50]
Could you please remove the Bus waiting station infront of FBI base.
Screenshot [Here](https://cdn.discordapp.com/attachments/538765556229341215/562368144598106152/unknown.png).
Thank you in advance.

**Comment by ghost** [comment]
Add the removeworldmodel code here

**Comment by ghost** [comment]
As said by Scorpyo it is not part of the world but rather the Bus driver script. It is not obstructing the usage of your base so i do not see the urge to get it removed.
