### ISSUE TITLE
San Andreas Pirates - Base request.

### ISSUE THREAD

**Issue by iMatizZ** [saesrpg/saesrpg-gang#51]
Hey yo ! We finally finished the mapping of our base , so we would like to request it. 

- Base files : https://files.fm/u/wmmu4fac 

- Spawn codes : https://pastebin.com/AkPJEVNf

**Comment by ghost** [comment]
Convert your base in lua and provide 1 zip file with all contents you want.

**Comment by iMatizZ** [comment]
@saesikz done , everything in this link: https://files.fm/u/h4j6jjck
