### ISSUE TITLE
S.W.A.T 2019 Requests

### ISSUE THREAD

**Issue by DenisIldis** [saesrpg/saesrpg-gang#53]
**SWAT 2019 Changes/Requests** 
_______________________________________________________________________________________________________________
**Spawns:**

Spawns code: https://pastebin.com/fSZQ00Tt
______________________________________________________________________________________________________

**Base & Base Shades:**

Base files/mapping: https://ufile.io/3pxdp

Base shaders code: https://pastebin.com/rCw4Xgn0

Shader 1: https://ufile.io/orrz3
______________________________________________________________________________________________________________

**Markers & Gates:**

Gates codes: https://pastebin.com/FCGbjcGh

Markers codes: https://pastebin.com/iXaBuDVH

______________________________________________________________________________________________________________

**Comment by DenisIldis** [comment]
Note: Skin shades will be updated in the future, and we would like to keep the current skin shades for now.

**Comment by ghost** [comment]
Choose a different walking style, 69 is banned due to abuse

**Comment by ghost** [comment]
Shader 1 file has expired. Mapping not converted to lua. Throw everything you want/have into 1 single __zip__ instead of 10 different links please.

**Comment by DenisIldis** [comment]
@saesikz Fixed, let me know if there's any problem.

**Comment by ghost** [comment]
Currently on hold due to size limit
