### ISSUE TITLE
Black~Bullets Billboard change

### ISSUE THREAD

**Issue by Ahmed-khayry** [saesrpg/saesrpg-gang#57]
we would like to change our billboard to this one

PNG: https://i.ibb.co/f9dKxBC/billboard-bb.png
dds: [Click here](https://mega.nz/#!kJlkjIQA!cmS7SNTng45CiOy9IbEuKUSvOo63vQQbM_OjN5JSYxU)

Thank you
regards/A7md

**Comment by SScorpyo** [comment]
[billb.dds](https://mega.nz/#!kJlkjIQA!cmS7SNTng45CiOy9IbEuKUSvOo63vQQbM_OjN5JSYxU)
