### ISSUE TITLE
CripZ - changes

### ISSUE THREAD

**Issue by laggiaze** [saesrpg/saesrpg-gang#58]
==CRIPZ BASE==
!ONLY EXTERIOR WILL CHANGE!
(gates,markers,interior will not change)

Download: http://fileload.info/fah1l9caq2o8
 ==BASE META==

	<script src="cripzlvl5.lua" type="client" />

==CRIPZ SPAWN CODE==

	<spawn id="CripZ OG" skin="190,269,297" x="383.44519042969" y="-2128.6130371094" z="7.8338875770569" rot="180" weapons="15,1;41,9999;24,250;27,250;31,450;28,350;46,1;34,150;16,10" description="Designated spawn for the official gang CripZ! Located in Los Santos If you aint BLUE you aint TRUE! CripZ are an organised crime gang that are a product of their environment. They do anything to get by, carjacking, murder, slinging dope and much more" r="0" g="80" b="87" restricted="gang,CripZ~" ganglevelrestriction="3" />

	<spawn id="CripZ" skin="190,270,269" x="366.42684936523" y="-2079.9670410156" z="7.8359375" rot="180" weapons="15,1;41,9999;24,250;27,250;31,450;28,350;46,1;34,150" description="Designated spawn for the official gang CripZ! Located in Los Santos If you aint BLUE you aint TRUE! CripZ are an organised crime gang that are a product of their environment. They do anything to get by, carjacking, murder, slinging dope and much more" r="0" g="85" b="85" restricted="gang,CripZ~" ganglevelrestriction="0" />

==NEW SKIN SHADERS==

	["CripZ"]={
		[190]={['fileName']='copgrl3.dds',['textureName']='copgrl3'},
		[269]={['fileName']='smoke.dds',['textureName']='smoke'},
		[270]={['fileName']='sweet.dds',['textureName']='sweet'},
		[297]={['fileName']='maddogg.dds',['textureName']='maddogg'},
	},

DOWNLOAD: https://mega.nz/#!ONxzyIaY!XWXvyYjQhHt_3yZdIrLXV60yCGzXA-YfEmaAyC52KUM

==GANG SPRAY TAG==

Spawn classes: [CripZ] - [CripZ OG]
Image preview:  https://i.imgur.com/h61TSnb.png
Image download: https://mega.nz/#!LEoBCYDD!-d73FiQkbe4OmuRKn31L7XgZPTTMI5i6oQUBrXcqkBs
Current organisation level: 5

**Comment by nicusi** [comment]
ID: 297 is modded John Cena skin, choose different, kthxbai
