### ISSUE TITLE
SAP Requests

### ISSUE THREAD

**Issue by DenisIldis** [saesrpg/saesrpg-gang#6]
So ahm, I'm speaking in the name of SAP HQ's & Managers.

We would like to get added to the criminal group (not criminal class) such as CLO, CEM and be able to attend JB's/BR's/SR's and so.

*Note:* This request has already been accepted by SAES GM's.

**Comment by ghost** [comment]
can you link or share where GM approved this ?
edit` i'v checked GM private channel but can't find a agreement on the suggestion suggestion was brought up but not really discussed and given a final decision

**Comment by DenisIldis** [comment]
Well, nicus told us that he informed SAES HQ's about GM's approval, however: 

https://imgur.com/a/OMEVXho
https://imgur.com/a/hc5iBR7
