### ISSUE TITLE
Outbreak Spawn Request

### ISSUE THREAD

**Issue by erentekingunduz** [saesrpg/saesrpg-gang#60]
### Hello dear Group Managers,
We, as the Outbreak Organization, would like to request a special spawn for our group. We'd like you to know that we fulfill all of the requirements set by you;
**Must have 22 active members:** ✔️ 
**Must have an active management team to represent the group within the community:** ✔️ 
**Must be active on the server for at least 4 months:** ✔️ 
**Must have attracted a mature memberbase and HQ team:** ✔️ 
**Must have a full media section with professional screenshots, roleplay and event logging, along with descriptions of what has happened:** ✔️ 
 **Must have expanded on the roleplay topic by creating a completely new scenerio and large roleplay event:** ✔️ 
All of the base/spawn files are ready. They can be found below.

### Base Files:
**Mapping** : https://www.dropbox.com/s/3qve8u3e6qec9wi/ob-base-request.rar?dl=0
**Mapping Shaders** : https://www.dropbox.com/s/uxga0x1mzp0iper/Base%20shaders.rar?dl=0
**Shaders' script** : https://pastebin.com/Ud4nmmZa
		
### ~~Gates/Doors~~ (Check the second post)
https://pastebin.com/iZXqdVNs

### ~~Markers~~ (Check the second post)
As for markers, we have a special request from you. As you may know, we had an idea for the base, which had been denied by the Group Managers team later then. As you guys didn't accept our previous base idea, we had to use the ex-base with some improvements, until we get a good one in LS, and as it's within our main role to jailbreak, we would like to add a marker to our base that teleports us to somewhere hidden in LS. The script below contains the LS-teleporter marker and a marker which stays inside the base.
Markers' script: https://pastebin.com/7CxnbhVm

### ~~Peds~~
~~If you allow us to have the LS-teleporter marker, we'd also like to have some peds staying there.
The first is going to be placed at "`1490.7, -1721.6, 8.2`" with "`160`" RotZ value. For the model, we'd like to have `skin id: 271`, doing the "`/lean`" animation. 
The second is going to be placed at "`1489.6, -1721.9, 8.2`" with "`90`" RotZ value.`Skin id :124`, with `/gtalk` anim.~~ **(Is no longer wanted.)**

### ~~Spawns~~ (Check the second post)
https://pastebin.com/Nuu6RdPu

### ~~Skin Shaders:~~ (Check the second post)
-> https://www.dropbox.com/s/pic1k1xwb9r41f8/ob1.dds?dl=0
`    ["Outbreak Rookie"]={
        [24]={['fileName']=ob1.dds',['textureName']='wbdyg1'},
    },`
-> https://www.dropbox.com/s/qf6i9kp0qjf27fc/ob2.dds?dl=0
`    ["Outbreak Member"]={
        [117]={['fileName']=ob2.dds',['textureName']='TRIADA'},
    },`
-> https://www.dropbox.com/s/5z349s8qlrvnf1w/ob3.dds?dl=0
`    ["Outbreak Distinctive"]={
        [297]={['fileName']=ob3.dds',['textureName']='maddogg'},
    },`
-> https://www.dropbox.com/s/9o16gc0d2js8gws/ob4.dds?dl=0
`    ["Outbreak HQ"]={
        [124]={['fileName']=ob4.dds',['textureName']='vmaff1'},
    },`

### Vehicles
We'd like to sort vehicles in-game, if possible.

### Extras
The usernames that should be added to acl group outbreak-hq -> `officialjosuea, velona77, cankutay123, percoso, rizacem`

We'd like to have all the criminal abilities to do jailbreaks and store robs, and assist in bank robs.

Also, we'd like to be able to sell weapons and drugs.

If anything is missing or broken, please let us know.
Outbreak HQ Team.

**Comment by erentekingunduz** [comment]
### UPDATES ->
**Spawn codes** : https://pastebin.com/N7EgQm5X
**Gates / Doors** : https://pastebin.com/YBu7mKfg
**Marker Code** : https://pastebin.com/erACxxas (Stays inside the base)
**We no longer want peds in Los Santos.**

## SKIN SHADERS:
-> https://www.dropbox.com/s/pic1k1xwb9r41f8/ob1.dds?dl=0
`["Outbreak Member"]={ [24]={['fileName']=ob1.dds',['textureName']='wbdyg1'}, },`
***
-> https://www.dropbox.com/s/qf6i9kp0qjf27fc/ob2.dds?dl=0
`["Outbreak Distinctive"]={ [117]={['fileName']=ob2.dds',['textureName']='TRIADA'}, },`
***
-> https://www.dropbox.com/s/9o16gc0d2js8gws/ob4.dds?dl=0
`["Outbreak HQ"]={ [124]={['fileName']=ob4.dds',['textureName']='vmaff1'}, },`

### ACL Groups
As we were told that ACL groups should not contain dots, we've changed them in our spawn codes.They are going to be;
`outbreak-hq`
`outbreak-dist`
`outbreak-member`
Usernames that are to be added to the outbreak-hq group are still the same, 
`officialjosuea, velona77, cankutay123, percoso, rizacem`

Please let us know if anything is missing or broken.

**Comment by erentekingunduz** [comment]
Spawn script is edited on the post above.

**Comment by teelor** [comment]
Will be live with the next update
