### ISSUE TITLE
Central Intelligence Agency - C.I.A. Forum Request

### ISSUE THREAD

**Issue by Ardron92** [saesrpg/saesrpg-gang#64]
Hello,

As we have gained level 1, would like to request a forum for CIA with the following spec:

Name: "Central Intelligence Agency"
Group HQ: Ardron
Status: Private

Also, a TS Channel named : Central Intelligence Agency

Thank you!

**Comment by saesrpgmta** [comment]
@Ardron92 I've done the group/forum on the website, any web changes need to go on the web issue tracker next time please.

**Comment by Ardron92** [comment]
@saesrpg ehm... our private forums have been posted in the.. groups part xD We are a squad afterall! So.. TSG? And yeah, sorry for that mistake

**Comment by saesrpgmta** [comment]
@Ardron92 This has now been corrected.
