### ISSUE TITLE
OverdoseCrime Hierarch Spawn selling ability and Joining announcement

### ISSUE THREAD

**Issue by Mrwann** [saesrpg/saesrpg-gang#72]
We'd like to add the drugs selling ability to the OverdoseCrime Hierarch spawn too, and also the announcement In the notification panel when someone joins the gang, Thanks.

We also want to change the skin shader In the Hierarch spawn, It's the same skin but just fixed since the tattoos are fucked up In SAES, Here's the skin..
![bestonewithouttattoos](https://user-images.githubusercontent.com/46716565/58487687-5427ff00-8168-11e9-8372-a9f8d74d624d.png)

**Comment by teelor** [comment]
Will be live with the next update
