### ISSUE TITLE
Comando da Capital Rewards Changes

### ISSUE THREAD

**Issue by VinnyBL** [saesrpg/saesrpg-gang#73]
Hi,
I would like to request a few changes for CDC rewards.
Most specifically,Shaders addition,skin change and spray tag change.

[Skin Change](https://pastebin.com/gnK2Xe4t)
The only change made is replacing the skin 219 for 193

[Skins Shaders](https://drive.google.com/file/d/1OzH6ddWChY6DPibhva3j6HVDGxmNg8Wz/view)
Shaders for the skins: 19,47,193

[Spray tag](https://drive.google.com/file/d/1QKAvmcDCzip-46pvtMS5lp-Yhg3ewDke/view?usp=sharing)

Preview: [Click](https://i.imgur.com/yJZV1rF.png)

That's all

**Comment by teelor** [comment]
Will be live with the next update
