### ISSUE TITLE
Underground Empire reward changes.

### ISSUE THREAD

**Issue by UE-Arctic** [saesrpg/saesrpg-gang#74]
### Skin shader
I've provided all skins in both dds and png format. There's a little notice about the girl skin, the skin uses two textures, one alpha cutout for jewelry and one bodymap for the character. the alpha cutout has been provided in .dds with dxt3 compression. The bodymap is standard .dds like the rest.

[Link](https://uploadfiles.io/fcvxik8s) to all the skins.
Information of the following skins.

**Primary - Underground Empire** 
Keep skin 240 (swmyri) already on the server, replace the rest with the following skins.
HFYRI - ID 40 - (hfyri.txd)
sOMYRI - ID 186 - (somyri.txd)

**Secondary - Underground Empire Commission**
torino - ID 295 - (torino.txd)
Add this to current selection or replace with present skin shader.

### Weapon setup
Change of golf club to hotdog for both spawns, Underground Empire & Underground Empire Commission.
From model ID 333 to 322 

### Walkstyle
Change to MOVE_BBBAT_M 65

**Comment by SAESMohd** [comment]
Secondary spawn was done but the rest are yet to be done
