### ISSUE TITLE
some raceTECH changes [minor]

### ISSUE THREAD

**Issue by SAES-Jay** [saesrpg/saesrpg-gang#75]
Can we make the gate at our base open to the public so anyone can enter, but at the same time disallow Police, Official Squads, SAI, Homeland Security, SAPA, DE and Government from entering? If this isn't possible then please leave the gate as it currently is.
Due to the wanted bug a lot of us are being harassed by cops at races (and give the fact they're illegal it's fine either way) but we don't have access to jail doors so we can't escape, can we have pls mens?

**Comment by ghost** [comment]
Can't do on the gates

**Comment by SAES-Jay** [comment]
Can we remove the gate instead? On second thoughts there is a public warp to and from the racetrack so trapping people in the base is a bit meh...

**Comment by teelor** [comment]
Will be live with the next update
