### ISSUE TITLE
The Company Skin Change

### ISSUE THREAD

**Issue by SScorpyo** [saesrpg/saesrpg-gang#77]
We would like to replace the skin id 186 on our both spawns ( *The Company* & *The Company High Council* )  with skin id `70`, model `wmosci`.
[THC3.dds](https://mega.nz/#!lR0l2K6B!MbQFbQoXqRdsagVrDYPSHq_6-E3g_OhxaqsFnUGb1Yk)

**Comment by teelor** [comment]
Will be live with the next update
