### ISSUE TITLE
ThC skin change 

### ISSUE THREAD

**Issue by SScorpyo** [saesrpg/saesrpg-gang#79]
We would like to replace the skin id `70` on our *The Company* spawn and skin id `228` on *The Company High Council* spawn with skin id `186` model `somyri`.
[THC1.dds](https://mega.nz/#!YZ8zDaBB!m4Fx-kp8MbGXdD2HBrtwGy2FvBKKoVYMtU-Qhk_6kPo)

**Comment by nicusi** [comment]
Again?

**Comment by ghost** [comment]
File no longer available to download. Please reupload

**Comment by SScorpyo** [comment]
updated, sorry

**Comment by nicusi** [comment]
Calma, I've sorted it  23 days ago orso 😊
