### ISSUE TITLE
Equipment for wardens

### ISSUE THREAD

**Issue by tut001** [saesrpg/saesrpg-gang#81]
Hello.

We would like to request sniper rifle on top of our current rewards for the PC Warden spawn. Any reasonable amount of ammo is fine.

- [ ] add sniper rifle to PC warden

We would also like to request 200 x M4 for trainee wardens to help assist with lethal force during jailbreaks. IIRC we had lethal weapon spawns for all police classes in one of the previous prisons.

- [ ] add M4 to trainee warden

regards SAPD HQ

**Comment by ghost** [comment]
As this is more of a general Server thingy I asked HQ to decide on this:

Verdict:
![image](https://user-images.githubusercontent.com/48806932/60761037-e6150880-a040-11e9-989c-e6b350482943.png)

**Comment by tut001** [comment]
right on
