### ISSUE TITLE
OverdoseCrime Reward Changes

### ISSUE THREAD

**Issue by Mrwann** [saesrpg/saesrpg-gang#88]
We'd like to change one of our current skins which Is
ID: 124
Name: vmaff1

and we wanna replace it with this one.
ID: 90
Name: wfyjg

http://www.mediafire.com/file/q2ksx26ikpuok3u/cbon1-sxs9s.dds/file

**Comment by nicusi** [comment]
Add .dds file

**Comment by Mrwann** [comment]
> Add .dds file

Done
