### ISSUE TITLE
Emergency Task Force reward requests

### ISSUE THREAD

**Issue by Vennelle** [saesrpg/saesrpg-gang#90]
**Dear SAES staff,**

Hereby i would like to request the rewards for ETF's level 1 acceptance,

1] 2 Police LV cars placed at LVPD next to my donated police cars.
2] A private forum named ''Emergency_Task_Force'' with the group HQ - Vennelle and i would like to have it set to private.
3] A TeamSpeak 3 channel called ''Emergency Task Force'' 

Thank you verry much for your time!

**Kind regards,
Vennelle.**

**Comment by ghost** [comment]
For forum: https://github.com/saesrpg/saesrpg-web/issues
TS3 @SAESKain

**Comment by Vennelle** [comment]
> For forum: https://github.com/saesrpg/saesrpg-web/issues
> TS3 @SAESKain

Sorry,  my bad, a new issue has been created in the correct section.
Thanks!

**Comment by nicusi** [comment]
Vehicle part is done.
