### ISSUE TITLE
The Pirus - Level 1 Rewards

### ISSUE THREAD

**Issue by SoulFly44** [saesrpg/saesrpg-gang#91]
- Dear SAES staff -
Desired rewards;
- 2 gang vehicles ( Huntley - Stratum )
- Teamspeak3 channel.
- A private forum for your gang.
https://saesrpg.uk/user/soulfly

**Comment by ghost** [comment]
For forum: https://github.com/saesrpg/saesrpg-web/issues
TS3 @SAESKain

**Comment by ghost** [comment]
Done
