### ISSUE TITLE
Mongols MC's reward requests

### ISSUE THREAD

**Issue by Sira188** [saesrpg/saesrpg-gang#92]
Hello there, as MMC got level one I am here to request the rewards.

1) First of all I would love to request 2 vehicles located on this location:
https://i.imgur.com/Ri6aJUp.png
https://i.imgur.com/6AO316m.png
1.1) First vehicle should be Picador
- Main color code : f9e9ac
- Second color code : 000000
- Nitro if it's possible
- No special wheels or etc..
1.2) Second vehicle should be Yosemite
- Main color code : f9e9ac
- Second color code : 000000
- Nitro is not needed.

2)A private forum named ''Mongols MC'' with our HQs : 
https://saesrpg.uk/user/sira
https://saesrpg.uk/user/ted
https://saesrpg.uk/user/carter

3)A TeamSpeak 3 channel called ''Mongols MC''

Kisses by Sira's bulgarian lips <3

**Comment by ghost** [comment]
For forum: https://github.com/saesrpg/saesrpg-web/issues
TS3 @SAESKain

**Comment by ghost** [comment]
Done
