### ISSUE TITLE
Clandestine Mob Reward Request

### ISSUE THREAD

**Issue by Noizi007** [saesrpg/saesrpg-gang#93]
Hello ,since C is now level 1 , we'd like to request our rewards which will be :
2 gang vehicles in our base :- Stratum with the colorcode #776017.
                                             -  Comet with the same colorcode as the previous one .
we also would like to have nitro upgrades on both of the vehicles.
- Teamspeak channel under the name Clandestine Mob 
Contact Jesse or Noizi for the level acceptance & vehicles cash ,thanks in advance.

**Comment by ghost** [comment]
Done!
