### ISSUE TITLE
FBI base - bus stop issue

### ISSUE THREAD

**Issue by IG8820** [saesrpg/saesrpg-gang#95]
Need the following bus stop removed from outside the FBI base. The object isn't a part of the FBI mapping or the vanilla GTA: SA map.

![mta-screen_2019-08-03_19-43-11](https://user-images.githubusercontent.com/47082717/62415777-1d1e1000-b627-11e9-9421-01f43d427868.png)

**Comment by IG8820** [comment]
Seems like this issue has been reported before by a previous FBI director and that the bus stop is a part of the bus driver script. If it's possible, could the GMs consider altering the script to have the bus stop positioned someone else nearby as its been a bit of a long term eye-sore for the FBI base. Even if it is just moved either 10-15m either way on the same pavement, it would be greatly appreciated.

Thanks Scorpyo for telling me about it. 👍

**Comment by ghost** [comment]
Honestly, Doesn't look that bad and it ain't blocking anything. If you can't live without this you can request a change to the script in the general issues: https://github.com/saesrpg/saesrpg/issues
