### ISSUE TITLE
OverdoseCrime changes

### ISSUE THREAD

**Issue by Mrwann** [saesrpg/saesrpg-gang#99]
We'd like to change one of our current skins which Is
ID: 29
Name: wmydrug

and we wanna replace it with this one.
ID: 240
Name: swmyri

and here's the shader:
https://www.mediafire.com/file/eb0xb1q6xlwdf1k/cbuco-x5xk8.dds/file

Also we'd like to change our spray tag to this one
https://i.postimg.cc/c449vwRg/ertreter.png

And one more thing, We've a marker upstair in our garage and It was locked to OC only, we'd like to make It public

Thanks

**Comment by SAESKain** [comment]
Shader still doesn't comply to sizing limits found here

https://saesrpg.uk/topic/5633/shader-size-limits

**Comment by Mrwann** [comment]
@SAESKain Yes right, Here's the fixed one
https://www.mediafire.com/file/9ba2a8sahdvuf3h/cbvij-5lzmw.dds/file

Plus, our new added girl skin was also over the limits, here's the fixed version
https://www.mediafire.com/file/vrkxr3xnhkuynbv/cbrpg-y6567.dds/file

**Comment by ghost** [comment]
Should have been done!
